### ISSUE TITLE
boost_signals library not found

### ISSUE THREAD

**Issue by Rahul0598** [ros/catkin#1031]
I am running Fedora 30 Workstation. I tried to install ROS melodic. The Step 2.1.2 - Building the catkin Workspace, fails. There are 2 errors that I can see from the terminal output
   1. Could not find the following Boost libraries: boost_signals
   2. Failed to process package 'tf2'

For the 1st error, I checked the `/usr/share/cmake/Modules/FindBoost.cmake` file, It has a single line referring to the signals headers : `set(_Boost_SIGNALS_HEADERS "boost/signals2.hpp")`. The file signals2.hpp exists in the boost directory, so that is not the issue. ROS, I guess, is not able to find this header file for some reason. I have installed boost libraries and all its dependencies via dnf (boost, boost-devel, boost-python3, boost-static and others)
For the 2nd error, I have installed the geometry libraries via dnf, it doesn't solve the issue.

I have tried to install Kinetic , melodic and fuerte. With kinetic - I get an opencv3 dependency issue, Melodic - the issue I've described here, fuerte - again has the issue with the boost_signals library. Any help would be much appreciated!
The following is the terminal output when I tried to install ROS melodic.

```
CMake Error at /usr/share/cmake/Modules/FindBoost.cmake:2165 (message):
Unable to find the requested Boost libraries.
    Boost version: 1.69.0
    Boost include path: /usr/include
    Could not find the following Boost libraries:
          boost_signals
Some (but not all) of the required Boost libraries were found. You may
need to install these additional Boost libraries. Alternatively, set
BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
to the location of Boost.

Call Stack (most recent call first):
CMakeLists.txt:6 (find_package)
-- Configuring incomplete, errors occurred!
See also "/home/devajji/ros_catkin_ws/build_isolated/tf2/CMakeFiles/CMakeOutput.log".
See also "/home/devajji/ros_catkin_ws/build_isolated/tf2/CMakeFiles/CMakeError.log".
<== Failed to process package 'tf2':
Command '['/home/devajji/ros_catkin_ws/install_isolated/env.sh', 'cmake', '/home/devajji/ros_catkin_ws/src/geometry2/tf2', '-DCATKIN_DEVEL_PREFIX=/home/devajji/ros_catk
in_ws/devel_isolated/tf2', '-DCMAKE_INSTALL_PREFIX=/home/devajji/ros_catkin_ws/install_isolated', '-DCMAKE_BUILD_TYPE=Release', '-DSETUPTOOLS_DEB_LAYOUT=OFF', '-G', 'Unix
Makefiles']' returned non-zero exit status 1
Reproduce this error by running:
==> cd /home/devajji/ros_catkin_ws/build_isolated/tf2 && /home/devajji/ros_catkin_ws/install_isolated/env.sh cmake /home/devajji/ros_catkin_ws/src/geometry2/tf2 -DCATKIN_
DEVEL_PREFIX=/home/devajji/ros_catkin_ws/devel_isolated/tf2 -DCMAKE_INSTALL_PREFIX=/home/devajji/ros_catkin_ws/install_isolated -DCMAKE_BUILD_TYPE=Release -DSETUPTOOLS_DEB_LAYOUT=OFF -G 'Unix Makefiles'
Command failed, exiting.
```

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.

**Comment by Rahul0598** [comment]
Link to question on answers.ros.org : https://answers.ros.org/question/333142/boost_signals-library-not-found/
