### ISSUE TITLE
pytest 5.1.0 generates incompatible xml output for catkin

### ISSUE THREAD

**Issue by Rayman** [ros/catkin#1032]
From pytest 5.1.0 (2019-08-15) the xml output of pytest changed [see this PR](https://github.com/pytest-dev/pytest/pull/5550). The output looks as follows:
```xml
<testsuites>
  <testsuite tests="5" failures="3" errors="1" skip="2" time="35" name="AllTests"></testsuite>
</testsuites>'
```
Note that the root element does not contain a summary, which catkin expects.

I would like to contribute a PR. Against which repo should it be, pytest or catkin?

**Comment by dirk-thomas** [comment]
Thank you for the report.

Also thanks for offering to work on a PR. I have recently addressed the same case in colcon/colcon-test-result#31. Since implementing the change was straight forward I just went ahead and created #1033. It would be great if you could give it a try and comment if it works for you.

(Since a new catkin release is imminent I want to make sure this gets included since otherwise it would likely be several months before another release.)
