### ISSUE TITLE
Install destinations 

### ISSUE THREAD

**Issue by jstiefel** [ros/catkin#1049]
I'm trying to figure out where my files should be installed to by the Cmake install() macro. I found this [list of catkin environment variables](http://docs.ros.org/jade/api/catkin/html/user_guide/variables.html) which are relative to the CMAKE_INSTALL_PREFIX. But how can I actually find the path of the install destinations to check if my files were successfully installed? I tried `echo $CATKIN_GLOBAL_INCLUDE_DESTINATION` or `echo $CMAKE_INSTALL_PREFIX` which outputs an empty line. 

I'm also wondering why I never had an install folder in my workspace yet. Should I change my CMAKE_INSTALL_PREFIX path when using ROS? I never read anything about this before.

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.

**Comment by jstiefel** [comment]
I misinterpreted the question label here. I created the topic on ROS Answers:
https://answers.ros.org/question/342050/catkin-install-destination/
