### ISSUE TITLE
check_tests_ran being called with bad arguments

### ISSUE THREAD

**Issue by kwc** [ros/catkin#105]
Note the '/' in the output file name.  This is from the devel builds

-- runtests.py: /opt/ros/fuerte/share/catkin/cmake/check_test_ran.py /home/rosbuild/hudson/workspace/ci-devel-ros_comm-fuerte-ubuntu-lucid-amd64/build/test_results/rostest/TEST-rostest__test_test/distro_version.test

**Comment by gerkey** [comment]
Yikes, that was horribly broken.  Fixed in ros_comm: https://code.ros.org/trac/ros/changeset/16492.

While I was at it, I added an explicit setting for ROS_TEST_RESULTS_DIR, to cause rostest to put the results where I ask check_test_ran to look for them.    In catkin, I've switched to using CATKIN_TEST_RESULTS_DIR.  We should consider modifying rostest to match.
