### ISSUE TITLE
ImportError: No module named catkin.environment_cache

### ISSUE THREAD

**Issue by dodsonmg** [ros/catkin#1056]
I'm building on a MacBook Pro running Catalina 10.15.2.

I'm following the OSX build instructions here:
https://wiki.ros.org/melodic/Installation/macOS/Homebrew/Source

I am at step 2.5.2 (Building the Catkin Workspace).

I provide the command:
```./src/catkin/bin/catkin_make_isolated --install -DCMAKE_BUILD_TYPE=Release -DCMAKE_MACOSX_RPATH=ON -DCMAKE_INSTALL_RPATH=$HOME/ros_catkin_ws/install_isolated/lib```

17 packages (of 54) install just fine, then I get the following error when building `rosboost_cfg`:

```
-- BUILD_SHARED_LIBS is on
Traceback (most recent call last):
  File "[$HOME]/melodic_catkin_ws/build_isolated/rosboost_cfg/catkin_generated/generate_cached_setup.py", line 20, in <module>
    from catkin.environment_cache import generate_environment_script
ImportError: No module named catkin.environment_cache
CMake Error at [$HOME]/melodic_catkin_ws/install_isolated/share/catkin/cmake/safe_execute_process.cmake:11 (message):
  execute_process(/usr/local/bin/python2
  "[$HOME]melodic_catkin_ws/build_isolated/rosboost_cfg/catkin_generated/generate_cached_setup.py")
  returned error code 1
Call Stack (most recent call first):
  [$HOME]/melodic_catkin_ws/install_isolated/share/catkin/cmake/all.cmake:208 (safe_execute_process)
  [$HOME]/melodic_catkin_ws/install_isolated/share/catkin/cmake/catkinConfig.cmake:20 (include)
  CMakeLists.txt:3 (find_package)
```

I have reviewed @mikepurvis work from a few years ago for `catkin_tools` (https://github.com/catkin/catkin_tools/issues/378) and the associated PR (https://github.com/catkin/catkin_tools/pull/391).

I'm having the problem with `catkin_make_isolated`, however, and am unsure how I could apply the changes from `catkin_tools`.

I think I'm having the same mutex problems as those previously reported:

If I run `catkin_make_isolated` with `--only-pkg-with-deps=rosboost_cfg`, it builds `catkin` and `rosboost_cfg` without any problems.

I then attempt to run `catkin_make_isolated` with `--ignore-pkg=rosboost_cfg` and it eventually chokes with `ImportError: No module named catkin.environment_cache` on `rosbuild`.

I attempt the same process on `rosbuild` (i.e., `--only-pkg-with-deps=rosbuild`), but there are enough dependencies there that I eventually get `ImportError: No module named catkin.environment_cache` while processing one of the dependencies.

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.

**Comment by dodsonmg** [comment]
Question posted to answers.ros.org:

https://answers.ros.org/question/342662/importerror-no-module-named-catkinenvironment_cache/
