### ISSUE TITLE
Issue "make file" #47

### ISSUE THREAD

**Issue by raialonso8** [ros/catkin#1082]
Hi,
I am using Ubuntu 18.04 and ros eloquent
I am trying to install catkind. First I tried with sudo apt-get install ros-eloquent-catkin however it looks that ros eloquent does not have a catkin package to install as it uses ament instead so I then followed the next tutorial:
https://index.ros.org/doc/ros2/Tutorials/catment/#combining-all-of-ros-and-ros-2-in-one-workspace-and-building-it-todo
It has a chapter called "Variation: Using the catkin API in a ROS 2 package" where tells you how to install catkin for ros2 as follows:

```
# install catkin_pkg
git clone https://github.com/ros-infrastructure/catkin_pkg.git
cd catkin_pkg
git checkout ament
python3 setup.py install --prefix $HOME/catkin --single-version-externally-managed --record foo --install-layout deb
# install catkin
git clone https://github.com/ros/catkin.git
cd catkin
git checkout ament
mkdir build
cd build
PYTHONPATH=$HOME/catkin/lib/python3/dist-packages/ cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/catkin -DPYTHON_EXECUTABLE=/usr/bin/python3
make install
```

However after following all the steps with succes when it comes to the last command "make install" it comes out with the following error:

CMake Error at gtest/cmake_install.cmake:47 (file):
file INSTALL cannot find
"/home/cpsr/catkin_pkg/catkin/build/gtest/libgtest.so".
Call Stack (most recent call first):
cmake_install.cmake:159 (include)

Makefile:94: recipe for target 'install' failed
make: *** [install] Error 1

Any clue or any help?
Thanks for your time

**Comment by dirk-thomas** [comment]
`catkin` is a ROS 1 package. `Eloquent` is a ROS 2 distribution.

---

I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.

**Comment by raialonso8** [comment]
I asked it in the link you left because your answer didn't answered my question
I know catkin is for ROS1 and eloquent is ROS2 but at the ros.org link i have attached it is said that it is possible to install catkin for ROS2

**Comment by dirk-thomas** [comment]
> at the ros.org link i have attached it is said that it is possible to install catkin for ROS2

Please note the very first sentence on that page:

> All that follows is experimental and speculative.

@gerkey FYI

**Comment by raialonso8** [comment]
I see, do you know anyway to install catkin for ROS2 apart from the one I mentioned?
Thanks for your answer

**Comment by dirk-thomas** [comment]
> do you know anyway to install catkin for ROS2 apart from the one I mentioned?

No, that is not recommended / supported.
