### ISSUE TITLE
How to handle deployement and changing path dependencies

### ISSUE THREAD

**Issue by Hugal31** [ros/catkin#1096]
I have this setup: I am using [Conan](https://conan.io/) to handle my dependencies, and some of them are ROS packages that uses catkin. The building and the packaging, and development workflow with Conan works fine.
 
However, when I deploy, I move my dependencies from `$HOME/.conan/data/.....` to `${CMAKE_INSTALL_PREFIX}/deps`, `/opt/mysoft/deps` for instance, so I can ship my software with its dependencies.

The problem (at least one of them) is that I when I run `/opt/mysoft/setup.sh`, it doesn't find my dependencies, because the `CMAKE_PREFIX_PATH` hard-coded in the _setup_util.py is wrong and points at `$HOME/.conan/data/....`, so it doesn't fill the `ROS_PACKAGE_PATH` with the content of `/opt/mysoft/deps/ros_dep_a`, `/opt/mysoft/deps/ros_dep_b`, etc...

First I thought about using the `local_setup.sh`, however it doesn't run the catkin hooks. It would if the `--extend` flag took the current `CMAKE_PREFIX_PATH` in account while searching for the hooks.

How can I do, or where can I find some documentation about this use-case ?

**Comment by dirk-thomas** [comment]
A `sh` script doesn't support determining its own location. Therefore the absolute path is being embedded into it at build time. You can either use any of the other shell scripts (e.g. `bash`) which support this or you can provide the path manually through an environment variable `_CATKIN_SETUP_DIR` (see https://github.com/ros/catkin/blob/100ece9dc3f56ae204329448a201a8973b3cef51/cmake/templates/local_setup.sh.in#L4-L6) before sourcing the `sh` script.

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.
