### ISSUE TITLE
How to support poetry / pyproject.toml?

### ISSUE THREAD

**Issue by dimaqq** [ros/catkin#1162]
Hi, I'd love to be able to write ros2/catkin-able components that use modern dependency management tools.

Specifically, I'd love to specify dependencies in `pyproject.toml` and use `poetry` to maintain/build/test the package.
(that would be as an alternative to `setup.py` and `

I could totally contribute some code towards this.

It's not yet supported, is it?

How do I go about that?

**Comment by Rayman** [comment]
Do you want to use `pyproject.yaml` to install dependencies? If so you should forward your request to https://github.com/ros-infrastructure/rosdep

Or to you want to replace `setup.py`? I don't think that will get implemented for ROS1 because it's end of line. You have a better chance to have https://github.com/colcon support it.

**Comment by dimaqq** [comment]
I was thinking about the latter.
Allowing modern 3p packages to be used in ros2 projects, for robotics devs.

The earlier is interesting too, and quite straightforward, may be a good first step 😉

**Comment by Rayman** [comment]
I found a related issue in the colcon project: https://github.com/colcon/colcon-core/issues/208

**Comment by ivanpauno** [comment]
> Allowing modern 3p packages to be used in ros2 projects, for robotics devs.

For ros2 see:

- https://github.com/colcon/colcon-core/issues/208
- https://github.com/colcon/colcon-core/issues/454

For ros1, I don't think this is going to be done, as noetic was the last release.
