### ISSUE TITLE
catkin wrapper macros for required data

### ISSUE THREAD

**Issue by tkruse** [ros/catkin#152]
In my opinion, it would be helpful if the CMakeLists.txt of small projects contained as little as possible data that is redundant or required anyway (most of the time). As such, I would prefer e.g.

catkin_install(TARGETS rospack rospackexeclone rosstackexe)

to

install(TARGETS rospack rospackexeclone rosstackexe
        ARCHIVE DESTINATION lib
        LIBRARY DESTINATION lib
        RUNTIME DESTINATION bin)

and

catkin_install(FILES manifest.xml stack.xml)

to

install(FILES manifest.xml stack.xml
        DESTINATION share/${PROJECT_NAME})

and 

catkin_stack(foo)

to 

project(foo)
catkin_stack()
catkin_project(foo)

**Comment by dirk-thomas** [comment]
stack/manifest.xml must not be installed manually - this is handled by catkin automatically.

For the install() and project() calls: the goal of catkin is to be as less invasive as possible.
Therefore catkin does not replace your vanila cmake project() call. the two functions catkin_stack() and catkin_project() will indeed be joined soon.

For the install() it is more tricky since now the destinations must conform to FHS and the user must either specify the correct path manually or (more desired) use a destination variable provided by catkin. This variable on the other hand makes the install() call anyway tied to catkin. So for the install a custom (set of) function(s) should be considered.

**Comment by dirk-thomas** [comment]
Closing this since it is preferred to write plain CMake instead of introducing more catkin-specific macros.
