### ISSUE TITLE
Add --src option to catkin_find

### ISSUE THREAD

**Issue by tfoote** [ros/catkin#183]
To locate the source directory of wet packages

**Comment by dirk-thomas** [comment]
We should not call the the option --src since that is not available in install space.

The idea is that catkin_find either:
- return a list of candidate paths where the the caller has to search in
- or the caller provides more specific information what he is looking for and catkin_find does the search in the candidate paths and returns only the matches.

**Comment by dirk-thomas** [comment]
Searching in source space is already performed when passing --share (at least when it is not an installspace).
I.e. for finding a package call:
  catkin_find PKGNAME package.xml
