### ISSUE TITLE
catkin_find does not correctly find files in src

### ISSUE THREAD

**Issue by tfoote** [ros/catkin#203]
I did a standalone install of std_msgs with CMAKE_PREFIX_PATH=/opt/ros/groovy

With the buildspace setup.bash sourced I got the following incorrect fall through to the installed version:

```
buildspace$ catkin_find std_msgs msg/Bool.msg
/opt/ros/groovy/share/std_msgs/msg/Bool.msg
```

After apt-get remove ros-groovy-std-msgs it returns nothing

```
buildspace$ catkin_find --share std_msgs msg/Bool.msg

```

And it does not list the source directory w/o the 2nd argument. 

```
buildspace$ catkin_find --share std_msgs
/tmp/std_msgs/build/buildspace/share/std_msgs
```

**Comment by tkruse** [comment]
Providing a fix in #212, but the current solution using catkin_pkg.packages.find_packages(basepath) over all known catkin workspace source locations is highly inefficient.

This bug shows the general problem with having a name tag in REP127, and a flexible folder name.

Since we went back to allowing hierarchical workspaces, we now have to crawl all source folders for package.xmls and then parse all these package.xmls to find one which has the correct name. This can be tweaked a lot with a single workspace knowing that mostly folder names will be equal to package names, but with n workspaces, all packages of overlaying workspaces need to have their package.xml parsed before proceeding to the next workspace.

**Comment by tkruse** [comment]
This seems to be almost fixed with 41c36787044b4ae9, except that the option first_matching_workspace_only needs to be used as default, with maybe a command line option to also show overlayed paths

**Comment by dirk-thomas** [comment]
catkin_find is used in several cases. What seems to be a reasonable default in this case might not be for other. So I would keep the option as it currently is.

**Comment by tkruse** [comment]
Tully raised this, so maybe Tully wants to comment on the desired behavior of
$ catkin_find std_msgs msg/Bool.msg

in the overlay case. In any case the behavior should be documented in the help, e.g. that by default even overlayed paths appear.

Currently the help is also misleading:

```
parser.add_argument('--first-only', action='store_true', help='Flag if only the results from the first matching workspace should be returned (default is all)')
 find_in_workspaces(... first_match_only=args.first_only...)
```

According to the help, the param passed to find_in_workspaces should be first_matching_workspace_only, not first_match_only. And there is no option to get only overlayed paths currently.

**Comment by dirk-thomas** [comment]
The question is what should be the default behavior?
We have three different use cases imho:
- rosrun: find first match (might return 0 or 1 results)
- roslaunch: find matches from one workspace in-order of chaining (might return 0-N results)
- CLI invocation: list all matches, don't stop on the overlaying workspace so that the user sees what is available (don't hide information from him)

Therefore I propose to use these two options:
`parser.add_argument('--first-only', action='store_true', help='Flag if only the first result should be returned')
parser.add_argument('--without-underlays', action='store_true', help='Flag if further workspaces should be skipped after finding matches in one workspace')`

**Comment by tkruse** [comment]
Maybe I am confused. I believe rosrun and roslaunch should only use overlaying files, never overlayed files. 
for rosrun, I think we search for executables named with a given name, and if the user is not careful there might be multiple such executables in candidate paths. For roslaunch, I think the same holds. In case of ambiguities both tools refuse to launch, asking the user to disambiguate I think.

I don't think roslaunch should ever launch a file from an overlayed package.

For CLI invocation, I humbly think that the rospack behavior of not listing overlayed files and paths is the least confusing. The whole purpose of overlaying is that by default files become hidden in my opinion, else the word "overlay" does not fit any more.

But maybe I mistake the whole purpose or catkin_find, and I do not know who already uses the command assuming that overlayed files are returned.

**Comment by tfoote** [comment]
I just talked this over with @dirk-thomas.

Looking at rosrun and roslaunch we get the backwards compatible behavior by
using --without-underlay so that rosrun and roslaunch find the right
packages.  The --first-only option is not needed, it provided the same
functionality for libexec which is the common use case.

I think keeping the full listing in catkin_find is beneficial for testing.
 All programmatic calls will use the --without-underlay and the user will
have the same experience using the user tools of rospack. roslaunch even
uses the API.  But catkin_find keeps the extra output so that the developer
who is debugging can see all results and know that things are being masked
out.  We should be clear in the docs what it is showing the full list.

On Mon, Nov 5, 2012 at 1:37 PM, tkruse notifications@github.com wrote:

> Maybe I am confused. I believe rosrun and roslaunch should only use
> overlaying files, never overlayed files.
> for rosrun, I think we search for executables named with a given name, and
> if the user is not careful there might be multiple such executables in
> candidate paths. For roslaunch, I think the same holds. In case of
> ambiguities both tools refuse to launch, asking the user to disambiguate I
> think.
> 
> I don't think roslaunch should ever launch a file from an overlayed
> package.
> 
> For CLI invocation, I humbly think that the rospack behavior of not
> listing overlayed files and paths is the least confusing. The whole purpose
> of overlaying is that by default files become hidden in my opinion, else
> the word "overlay" does not fit any more.
> 
> But maybe I mistake the whole purpose or catkin_find, and I do not know
> who already uses the command assuming that overlayed files are returned.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ros/catkin/issues/203#issuecomment-10089040.

## 

Tully Foote
tfoote@willowgarage.com
(650) 475-2827

**Comment by dirk-thomas** [comment]
When listing the possible results I was talking about the specific catkin_find invocation in rosun. It is called with `--libexec` to there is by definition only one result per workspace. Even if it was using `--first-only` it is semantically performing `--without-underlay`.

Based on the returned basepath of the searched package than the binary is searched as it was before. That code can still return multiple matches and therefore as the user to choose.

Even if `-first-only` will not be used currently I will keep it for now.

**Comment by tfoote** [comment]
That seems fine.

On Mon, Nov 5, 2012 at 2:19 PM, Dirk Thomas notifications@github.comwrote:

> When listing the possible results I was talking about the specific
> catkin_find invocation in rosun. It is called with --libexec to there is
> by definition only one result per workspace. Even if it was using
> --first-only it is semantically performing --without-underlay.
> 
> Based on the returned basepath of the searched package than the binary is
> searched as it was before. That code can still return multiple matches and
> therefore as the user to choose.
> 
> Even if -first-only will not be used currently I will keep it for now.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ros/catkin/issues/203#issuecomment-10090729.

## 

Tully Foote
tfoote@willowgarage.com
(650) 475-2827

**Comment by tkruse** [comment]
Just to make sure I understand: rospack will be a tool for users, whereas catkin_find will be a tool for developers / debuggers, is that correct?
So rospack will never ever go away, and not ever be replaced by catkin_find for mere users?

**Comment by dirk-thomas** [comment]
catkin_find is currently providing the functionality which is missing from all the other tools (rospack, roslib, rospkg).

In a perfect world all of these would be redesigned and consolidated since the current code and their interaction is pretty bad. But the questions will be if this refactoring will ever happen or we just keep it the way it is now until we replace all of that in ROS 2.0 anyway.

**Comment by tkruse** [comment]
I am asking because the CLI syntax should be future proof, IMO. So if in the future we expect catkin_find to become a user tool, the command structure should as of now be prepared for that.

So if we think for users, the default behavior should be only to show overlays, we should do that now, even if that is annoying for developers right now. Because else we will have another migration step in the future, where we either need to introduce another command (changing docs), or change any client script. 

I might be too worried about this, just giving it as consideration, and will not mention it again.

**Comment by dirk-thomas** [comment]
I would agree with Tully: the user should see everything by default.

It is easier for the user to conclude that the first group of results overlays the other than to understand that there are other things below which he does not see (until using a magic option).
