### ISSUE TITLE
change name of buildspace/setup.py and catkin/templates/setup.py

### ISSUE THREAD

**Issue by tkruse** [ros/catkin#221]
the name setup.py is taken by distutils/setuptools, using it for other purposes is confusing, as any reference to setup.py in docs and code comments becomes ambiguous.

Ideally, both files are renamed to different names each as well for better communication about them.

Also, buildspace/setup.py might be better rewritten as mere shell script.

**Comment by dirk-thomas** [comment]
Since the shell scripts are names setup.EXT what would you propose for the corresponding Python file (if not setup.py)?

Why should it be rewritten as a shell script? The script computes not only trivial stuff - implementing it in shell script is not only difficult and cumbersome but also requires it to be implemented multiple times (for different platforms like Windows).

**Comment by tkruse** [comment]
I have to think about a better name, but something like workspace_util or so seems just as well.
As to the shell script, I am not talking about templates/setup.py which has complex logic, but buildspace/setup.py, which is generated by cmake/templates/script.py.in (not a good name either).

**Comment by dirk-thomas** [comment]
Both files you mentioned are essentially the same. The file cmake/templates/setup.py is copied to installspace as setup.py. Since we want to avoid copying files from source- to buildspace the setup.py under buildspace is just a relaying script to cmake/templates/setup.py.

Therefore both files - setup.py in build- and installspace - should have the same name. Sure that file could be named workspace_util.py or just util.py. May be we should wait with this until #208 has been closed.

**Comment by tkruse** [comment]
In my opinion util.py is a very bad name for a python module/script living
outside a python package. Given it only exists for setup.sh, I vote for
setup_util.py

I cannot tell whether it really makes much sense to have a relay at all,
rather than having setup.sh use an absolute path to the right setup.py in
any case, since it uses an absolut path anyway. But to make both buildspace
and installation most similar, maybe that's okay, and explains why to still
use a python script.

**Comment by tkruse** [comment]
Actually, setup_utils.py is still not great because it makes bash tab completion a bit annoying, because the user has to also type the dot. Sorry for not noticing before. A name like _setup_utills.py might be better.

**Comment by dirk-thomas** [comment]
I agree that the current name is not good for auto completion. I dont know if I like an underscore prefix. Probably a plain name (which does not start with s) is better - like `util.py`.

**Comment by tkruse** [comment]
I'd say ask 2-3 people at willow garage, that should give us a balanced
view.
