### ISSUE TITLE
Header only packages should only be build_depend, not run_depend?

### ISSUE THREAD

**Issue by stonier** [ros/catkin#260]
Currently a package that contains header files only (like eigen, it may be a template header library) should be a build time dependency only. If you put such a package as an arg in the catkin_package CATKIN_DEPENDS (so you can get the include directories passed down the line) and as a build_depend in the package.xml, catkin complains that it is not listed as a run_depend dependency.

```
CMake Error at /opt/ros/groovy/share/catkin/cmake/catkin_package.cmake:150 (message):
  catkin_package() DEPENDS on the catkin package 'ecl_mpl' which must
  therefore be listed as a run dependency in the package.xml
Call Stack (most recent call first):
  /opt/ros/groovy/share/catkin/cmake/catkin_package.cmake:77 (_catkin_package)
  ecl_core/ecl_type_traits/CMakeLists.txt:13 (catkin_package)
```

This is of course, assuming that build_depend and run_depend by definition are exactly build and runtime dependencies. Probably this is related to #233.

**Comment by dirk-thomas** [comment]
The assumption that heades-only would be build-only dependencies is not completely correct.

If you need the headers of a package only in your cpp files to build a library or executable than yes, this would only be a build time dependency. In this case you must not declare it under (CATKIN_)DEPENDS since you do not want to expose this dependency to downstream packages.

As soon as you want to expose it to downstream package it must also be a runtime dependency. This is usually the case if you include the header inside of your own headers. Since downstream projects include the headers transitively the dependency is also necessary at runtime.

**Comment by jbohren** [comment]
"Since downstream projects include the headers transitively the dependency is also necessary at runtime." 

Can you explain why this makes it necessary at runtime? Don't headers normally only get "included" at buildtime? Or does "runtime" mean all time after THIS package is built? If that's the case, then this naming is really confusing.

**Comment by stonier** [comment]
Dirk, is this something conceptually that I'm not getting? 

Or is it just a constraint in the way catkin must currently expose headers to downstream packages? I agree with jbohren - it's really unintuitive that a package akin to something like 'eigen' should either be declared as a runtime dependency, or explicitly labelled as a dependency by packages who only use it indirectly through other packages.

If it is just a constraint in the way catkin currently does things, may this be tagged as something that can be improved?

**Comment by tfoote** [comment]
The issue is that we don't separate the runtime and devel packages.  If we
did this it would not be a problem.

Build depends means that these are packages that are needed at build time
for your package.  Run depends are those needed when you are going to be
run.  Any time a package is installed it gets it runtime dependencies
installed.

The "solution" is that you would have foo and foo-dev  where foo does not
export the headers and other packages have runtime depends onto it.  And
foo-dev exports the headers and would be a build depends of any package
using those headers.

As we haven't separated the runtime and development packaging we require
anything that you export to downstream packages to be in your runtime
dependencies, otherwise the downstream packages are not guaranteed to
build.  The path forward is for us to separate the packages, which is the
standard practice for linux packaging.  However this requires the
maintainer to do the work to make the separation cleanly, and in the future
we can look to upgrading the toolchain to make separate packages, but we
need to do one step at a time.

On Sun, Nov 18, 2012 at 9:35 AM, Daniel Stonier notifications@github.comwrote:

> Dirk, is this something conceptually that I'm not getting?
> 
> Or is it just a constraint in the way catkin must currently expose headers
> to downstream packages? I agree with jbohren - it's really unintuitive that
> a package akin to something like 'eigen' should either be declared as a
> runtime dependency, or explicitly labelled as a dependency by packages who
> only use it indirectly through other packages.
> 
> If it is just a constraint in the way catkin currently does things, may
> this be tagged as something that can be improved?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ros/catkin/issues/260#issuecomment-10488658.

## 

Tully Foote
tfoote@willowgarage.com
(650) 475-2827

**Comment by stonier** [comment]
Kind of guessed that - thanks for the confirmation Tully.

I added a footnote to the roswiki for [package.xml](http://ros.org/wiki/catkin/package.xml) explaining and referring back to this discussion.

**Comment by jbohren** [comment]
Simple question: when does "buildtime" of package X end and "runtime" of package X start? Is it after everything in package X has been built, but before any of its dependants have been built?

**Comment by tfoote** [comment]
It's not a sequence necessarily.  Built time is anytime you're trying to
compile the package.  Runtime is when you're executing elements of the
package or dependent packages, it can either be from the devel space or
install space.

If you're working from source you're usually have both build and run
depends installed.  If you're using the precompiled binaries you usually
only have the run depends installed.  On the buildfarm you only have the
build depends installed.

On Sun, Nov 18, 2012 at 7:32 PM, Jonathan Bohren
notifications@github.comwrote:

> Simple question: when does "buildtime" of package X end and "runtime" of
> package X start? Is it after everything in package X has been built, but
> before any of its dependants have been built?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ros/catkin/issues/260#issuecomment-10500408.

## 

Tully Foote
tfoote@willowgarage.com
(650) 475-2827

**Comment by jbohren** [comment]
> It's not a sequence necessarily. Built time is anytime you're trying to
> compile the package. Runtime is when you're executing elements of the
> package or dependent packages, it can either be from the devel space or
> install space.

Then, does compiling a dependant package fall into the "runtime" category?

**Comment by tfoote** [comment]
As I think you mean it yes.  if you're building some other package its that
package's buildtime. As buildtime and runtime are contextual its probably
better to be mote explicit as to the situation.

The better way to say it is that all the run depends of a package's build
depends will be installed with the build depends.

**Comment by jbohren** [comment]
That doesn't really answer my question, which doesn't really have to do with installation, but the following example does.

Consider the following sandboxed situation:
- [sbox1](https://github.com/jbohren/catkin_sandbox/blob/master/sbox1) contains only a header file called [sbox1.h](https://github.com/jbohren/catkin_sandbox/blob/master/sbox1/include/sbox1/sbox1.h)
- [sbox2](https://github.com/jbohren/catkin_sandbox/blob/master/sbox2) builds a library called `libsbox2` and includes [sbox1.h](https://github.com/jbohren/catkin_sandbox/blob/master/sbox1/include/sbox1/sbox1.h) in header [sbox2.h](https://github.com/jbohren/catkin_sandbox/blob/master/sbox2/include/sbox2/sbox2.h)
- [sbox3](https://github.com/jbohren/catkin_sandbox/blob/master/sbox3) builds an executable called `sbox3` from [sbox3.cpp](https://github.com/jbohren/catkin_sandbox/blob/master/sbox3/sbox3.cpp) linked against `libsbox2` and includes [sbox2.h](https://github.com/jbohren/catkin_sandbox/blob/master/sbox2/include/sbox2/sbox2.h), and transitively [sbox1.h](https://github.com/jbohren/catkin_sandbox/blob/master/sbox1/include/sbox1/sbox1.h)

In this case, `sbox1` needs to be a "run" dependency of `sbox2` despite the fact that there's nothing in `sbox2` that can be "run" in most senses of the term. [This is the counter-intuitive part](https://github.com/jbohren/catkin_sandbox/blob/master/sbox2/package.xml#L14).

The confusion is that dependencies of sbox2 that are needed when sbox3 is built are considered "run" dependencies. In this case, "run" seems to mean "anything needed for anything that can happen after sbox2 is built" 

You can see the whole example here: https://github.com/jbohren/catkin_sandbox

**Comment by jbohren** [comment]
I also just added an example that shows what happens if you properly insulate the headers by only include the headers from `sbox1` in the `sbox2.cpp` file as seen here in [sbox2_alt](https://github.com/jbohren/catkin_sandbox/blob/master/sbox2_alt). This is also a good example of the different ways that build and run dependencies manifest themselves in the CMakeLists.txt,

**Comment by tkruse** [comment]
IIRC, the label run_depend was indirectly taken from the Java world in the
buildsystem SIG discussion, where no header files exist. It seems in the
light of this discussion that the label is confusing for our (c++) purposes.
So I suggest we change it to reduce confusion.

To not impact groovy release, we can define a valid alias for run_depend to
be used in docs and tutorials, so no need to reject this because of groovy
release delays, if an alias is acceptable.

I would suggest install_depend, meaning dependencies that must be there for
a package to be installable after build. In any case the docs, the examples
(e.g. in catkin_pkg templates) and tutorials should be adapted to make this
clear, IMHO.

**Comment by dirk-thomas** [comment]
`install_depend` does not reduce the confusion since `run_depend` also applies when no installation is involved at all (i.e. when run from devel spaces only).

**Comment by tkruse** [comment]
If I understand correctly, in the non-installation case, run_depend changes
some cmake variables, is that what you mean, or are there more implications.

We can ask the buildsystem sig for other names. My next attempt would
involve the word "export" i guess.

**Comment by jbohren** [comment]
Name ideas:
`use_depend`
`post_build_depend`
`product_depend`
`depend`

**Comment by dirk-thomas** [comment]
-1 for the following:
`post_build`: has a very different meaning in the context of building already.
`product`: I can't see any relation for that term?
`depend`: too generic when there is also a build/buildtool/test_depend.

-0.5 for:
`use_depend`: a build dependency could also be considered "used at buildtime" so the difference is not clear with this either.

**Comment by tfoote** [comment]
As much as the naming is not exactly right, I don't think that any single
word is going to exactly capture the intent.  And as such we are going to
need to document the semantics well.  This naming went through our review
and for now lets stick with it.  Changing names has a significant cost to
both developers and users and we need to keep that in mind any time we
consider changing a name.  It's always of interest to optimize the naming
but I think there are other places where we should focus our efforts going
forward after documenting the current notation clearly.

On Wed, Nov 21, 2012 at 5:52 AM, Dirk Thomas notifications@github.comwrote:

> -1 for the following:
> post_build: has a very different meaning in the context of building
> already.
> product: I can't see any relation for that term?
> depend: too generic when there is also a build/buildtool/test_depend.
> 
> -0.5 for:
> use_depend: a build dependency could also be considered "used" so the
> difference is not clear with this either.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ros/catkin/issues/260#issuecomment-10597512.

## 

Tully Foote
tfoote@willowgarage.com
(650) 475-2827
