### ISSUE TITLE
CTest integration

### ISSUE THREAD

**Issue by vrabaud** [ros/catkin#266]
CTest is now pretty standard for testing in CMake (at least since 2.8.0 which is what we support for Fuerte and above):
http://cmake.org/Wiki/CMake/Testing_With_CTest

You would need to call enable_testing() in the toplevel.cmake and use the add_test macro in the catkin test macros.

Advantages of using CTests compared to what we have:
- handles any kind of test (gtest, nosetest, anything random that should basically not error out if the test passes). add_test therefore helps making the code more catkin independent.
- I know I have some tests that are defined without the catkin macros and I have to run my tests in two batches: the standard way and the catkin way (make run_tests and ctest).
- way less targets (as there is one created per test macro call for now .... which is messy). CTest uses regular expressions to filter out the tests you want: e.g. ctest -R my_regex
- CTest can multi-thread the test execution

Any thoughts ?

**Comment by isucan** [comment]
I'd like to be using ctest  :+1:

**Comment by dirk-thomas** [comment]
The disadvantage of using ctest with plain binaries rather than gtest binaries is the lack of unit test result output. It only exposes a simple True/False.

Anyway #448 includes the call to `enable_testing()` and uses `add_test()` internally for all kind of tests (gtests, nosetests, rostests).
@vrabaud Would you like to give the pull request a try and see if it does what you expect?

**Comment by dirk-thomas** [comment]
Implemented as of #448.
