### ISSUE TITLE
isolated install space takes an eternity to source setup.sh

### ISSUE THREAD

**Issue by tkruse** [ros/catkin#289]
It seems that there are plenty of redundant operations occuring recusively. I looked at the setup.sh files that get sourced, and they look very similar to each other, so I cannot tellwhich part are actually relevant.

It is this part that takes so long, because sourcing each other setup.sh also takes long.(Note in the current code, setup.$CATKIN_SHELL is sourced, which also does not help, but is not the cause for the wait.

```
# source setup.SHELL from parent workspaces
if [ $IS_RECURSIVE -eq 0 ]; then
  _CATKIN_SETUP_NO_RECURSION=1
  for workspace in $("$SETUP_UTIL" --get-reversed-workspaces --value "/home/kruset/groovy_underlay/install_isolated"); do
    echo $workspace
    . "$workspace/setup.sh"
  done
  _CATKIN_SETUP_NO_RECURSION=0
fi
```

**Comment by dirk-thomas** [comment]
Obviously the files look similar since they are being generated from the same template. But non of the operations performed is redundant.

Each workspace has its own setup files and it performs only workspace-specific changes of the environment. For an isolated build with potentially hundreds of chained workspaces the time to source all of them adds up linearly.

Potential speed improvement will require the whole environment generation process to be redesigned in order to not scale with the number of workspaces.

**Comment by dirk-thomas** [comment]
Can you confirm that the current `refactor_setup` branch solves that for you, too?

**Comment by tkruse** [comment]
I confirm this branch solves it for me, takes less than a second.
