### ISSUE TITLE
Add ROS_WORKSPACE variable to catkin workspace setup scripts

### ISSUE THREAD

**Issue by bgromov** [ros/catkin#294]
At the moment the lack of `ROS_WORKSPACE` environment variable breaks the functionality of `roscd` called without arguments. However such functionality would be very useful in case of complex folder structures, e.g. while using several ROS distros with multiple workspaces etc.

Probably, in this case `ROS_WORKSPACE` should point to a top-level directory of catkin workspace.

**Comment by tkruse** [comment]
Abstracting the idea here, the real request is for a useful behavior of roscd without arguments. This could be achieved in other ways than by setting ROS_WORKSPACE, maybe.

This should work with wet, dry-on-wet, dry-after-wet and wet-after-dry use-cases (wet=catkin, dry=rosws). Meaning there'd need to be a reliable means of detecting workspace activation across wet and dy workspaces. Given REP130, we have at least settled on ROS_WORKSPACE being unset by catkin workspace activation, so we could attempt for roscd to check for ROS_WORKSPACE first, and when that fails, use catkin_pkg logic to jump to some central folder.

For certain reasons it had been decided that catkin_make was to be invoked in a catkin root folder (rather than the build space). but it might still make sense to roscd into the build space when no roscd arguments are given and we are in a devel space environment So that user can quickly roscd into a location where they can trigger a rebuild, and "cd -" back to where they were.

**Comment by tkruse** [comment]
Referred to by question here.
http://answers.ros.org/question/51463/ros_workspace-is-not-supported-with-catkin-workspaces/

**Comment by dirk-thomas** [comment]
As Thibault mentioned above roscd should be modified to use the existing catkin env variables to provide reasonable behavior when ROS_WORKSPACE is not set. catkin has and should not have any knowledge about ROS_WORKSPACE.

**Comment by tkruse** [comment]
Dirk, if you declare which catkin (or catkin_pkg) command should be used
for this purpose by roscd, we can open a ticked on roscd with that detail
and close this ticket.

**Comment by dirk-thomas** [comment]
There is no ready-to-use command. You might want to get a list workspaces via `catkin_pkg.workspaces.get_spaces()` and then decide which one to pick, i.e. the first source space? But I don't see any way to find the build space for them.

**Comment by dirk-thomas** [comment]
ros/ros_comm#123

**Comment by tkruse** [comment]
Yes, which is why I think this shoud remain a catkin (or catkin_pkg) open usability issue. It should not be the task of roscd to create a hack to find the build space (or workspace root). I understand catkin does not currently provide a means to get there cleanly, and this ticket means that catkin should be changed to proived such a way.

Curretnly catkin only provides a runtime environment via setup.sh files, but this ticket says catkin should provide a buildtime environment, with an env var or something similar that helps building the packages conveniently, meaning either a global catkin_make command (similar to rosmake), or an easy way to roscd into a folder where the user can make or catkin_make his packages.

Note that I for one would love to even see an integrated command that rebuilds both dry and wet packages with a single command invocation, but that's for the long-term future.

**Comment by tfoote** [comment]
@tkruse it's been reticketed at ros/ros_comm#123 for the usability with
roscd.  There's not roscd type capability currently built into catkin at
all.  That would be a separate enhancement to be discussed.

On Sun, Jan 13, 2013 at 3:20 AM, tkruse notifications@github.com wrote:

> Yes, which is why I think this shoud remain a catkin (or catkin_pkg) open
> usability issue. It should not be the task of roscd to create a hack to
> find the build space (or workspace root). I understand catkin does not
> currently provide a means to get there cleanly, and this ticket means that
> catkin should be changed to proived such a way.
> 
> Curretnly catkin only provides a runtime environment via setup.sh files,
> but this ticket says catkin should provide a buildtime environment, with an
> env var or something similar that helps building the packages conveniently,
> meaning either a global catkin_make command (similar to rosmake), or an
> easy way to roscd into a folder where the user can make or catkin_make his
> packages.
> 
> Note that I for one would love to even see an integrated command that
> rebuilds both dry and wet packages with a single command invocation, but
> that's for the long-term future.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ros/catkin/issues/294#issuecomment-12192411.

## 

Tully Foote
tfoote@willowgarage.com
(650) 475-2827
