### ISSUE TITLE
catkin_make_isolated --merge does not generate message include folder

### ISSUE THREAD

**Issue by tkruse** [ros/catkin#332]
Not sure whether this might be a genmsg issue.

To reproduce:

```
mkdir issue_ws
cd issue_ws/
mkdir src
cd src
git clone https://github.com/ros/std_msgs
git clone https://github.com/ros/catkin
git clone https://github.com/ros/genmsg
git clone https://github.com/ros/gencpp
git clone https://github.com/ros/genpy
git clone https://github.com/ros/genlisp
git clone https://github.com/ros/message_generation
cd ..
src/catkin/bin/catkin_make_isolated --merge
ls devel_isolated
```

This yields for me (today, with -- catkin 0.5.63):

```
$ ls devel_isolated/
bin/  env.sh*  etc/  lib/  setup.bash  setup.sh  _setup_util.py*  setup.zsh  share/
```

So no include folder (or headers) here, nor anywhere else I looked.

The same as above without --merge yields:

```
$ ls devel_isolated/std_msgs/include/std_msgs/
Bool.h
...
```

Since only the --merge option causes this, I assume a catkn issue, not genmsg issue.

**Comment by tkruse** [comment]
Please also note: If I repeat the steps above, but sourcing /opt/ros/groovy/setup.bash first, yet still invoke src/catkin/bin/catkin_make_isolated, the error does not occur. And this does not feel right, neither. It seems catkin is not properly overlayed there. Should I raise a separate ticket for that?

**Comment by dirk-thomas** [comment]
It is not an overlaying issue. Before it was usually an issue when you build, source and rebuild the same workspace because your previous build affects your next build. Therefore catkin tries to remove the devel space from the CPP (since roughly three months).

Since we have merged devel spaces now it seems to be that we have to trade that side effect for the feature that the devel space might should still be used since it was already populated by a parent workspace. @wjwwood do you recall the discussion some months ago? I think we have no choice but to allow the devel space in CPP when it is already set. The side effect for the use case build, source and rebuild is than something we have to live with, right?

**Comment by dirk-thomas** [comment]
Just for the record the specific issue is that catkin removes the devel space from the CPP. This is usually a good idea to avoid potential self-overlaying when doing build, source, rebuild of the same workspace.

For merging the develspace is populated by the parent workspaces. When the devel space is than ignored genmsg does not find any generators and therefore does not generate headers, Python file and their specific folders.

**Comment by tkruse** [comment]
Can you explain the side-effect of build/source/rebuild? Is this about artifacts left over from first build, which are never cleaned up, so when the second build would not generate them, they still linger around? Are there more problems than those?

**Comment by dirk-thomas** [comment]
If you build a workspace, than source its setup and call rebuild you will potentially find and use things from that workspace which is not the case for a fresh workspace.

**Comment by tkruse** [comment]
Can you tell me specific examples would be found and used from a used develspace? I assume no catkin package calls find_package on itself, so I will guess that it is not xyzConfig.cmake files we talk about. So what else to be created in a develspace is also consumed when present?

**Comment by dirk-thomas** [comment]
Potentially anything which is available in the devel space: CMake modules, package.xml files, Python code, headers, libraries...
