### ISSUE TITLE
Raise Error on missing build_depend, warning on superfluous

### ISSUE THREAD

**Issue by tkruse** [ros/catkin#334]
It would be nice if catkin_package raised an error for any catkin package the user has find_packaged but not declared as build_dependency, and raised a warning if declared as build_dependency but never find-packaged.

As design sketch, I suggest that pkgConfig.cmake does something like this:

```
if(not ${PROJECT_NAME}_IN_FIND_PACKAGE)
  # set some variable here
endif()
set(${PROJECT_NAME}_IN_FIND_PACKAGE TRUE)
#rest of config here, including other calls to find_package)
set(${PROJECT_NAME}_IN_FIND_PACKAGE FALSE)
```

That way, all non-transitive dependencies can be captured and compared to those in package.xml. Regarding system dependencies that are in package.xml would obviously never be marked, I hope we can extend the package.xml syntax to treat those differently to either suppress the warning or declare a valid prefix to check against all <PREFIX>_FOUND variables.

**Comment by dirk-thomas** [comment]
The CMake config for catkin does perform the check for missing build deps. Each packages CMake config is unable to perform that kind of check since it doesn't know if it is called as a direct or indirect dependency.

Warning about "superfluous" build deps is not possible since you can not judge when it is not used.
