### ISSUE TITLE
ROS_WORKSPACE is unset by setup.sh in rosws workspace

### ISSUE THREAD

**Issue by bgromov** [ros/catkin#356]
Relevant question on [ROS Answers](http://answers.ros.org/question/54523/trouble-creating-sandbox-in-groovy/)

**Comment by jbohren** [comment]
It looks like the line that unsets ROS_WORKSPACE is line 39 in:

```
/opt/ros/groovy/etc/catkin/profile.d/10.ros.sh
```

This happens regardless of whether you're using a catkin or rosbuild workspace.

**Comment by dirk-thomas** [comment]
Since the above mentioned file is a catkin environment hook that is only happening when sourcing a catkin based workspace.

That catkin workspaces unset ROS_WORKSPACE is actually intended behavior and has been specifically added. Else sourcing a wet groovy workspace after having sourced a dry whatever workspace would have ROS_WORKSPACE still be set to the old path.

Unsetting the variable is a convenience to prevent wrong information when switching between environments. Whatever tools is using ROS_WORKSPACE is responsible to set that environment variable. May be @tkruse can comment on why the variable is not set or how the describe usage must be different.

**Comment by tkruse** [comment]
replied on answers, and created ticket at https://github.com/vcstools/rosinstall/issues/57
the rosws generated setup.sh sets ROS_WORKSPACE but after that source groovy's setup.sh, which unsets again. the rsows generated setuo.sh must set ROS_WORKSPACE after sourcing other setup files.
