### ISSUE TITLE
catkin docs missing

### ISSUE THREAD

**Issue by jack-oquin** [ros/catkin#384]
I was looking for `catkin_add_nosetests()`, but the documentation was nowhere to be found.

Apparently, none of the generated CMake macro docs are being built and stored anywhere.

**Comment by dirk-thomas** [comment]
They are generated and stored as part of the static docs for catkin. I reran the catkin doc deployment to make sure everything is up-to-date (even if it was already on the latest version 0.5.64).

I think the page you are looking for is: http://ros.org/doc/groovy/api/catkin/html/dev_guide/generated_cmake_api.html
I got there from: http://ros.org/wiki/catkin, Code API, Extracted CMake API reference.

**Comment by jack-oquin** [comment]
The page you mention is two levels deep from the catkin wiki page and misleadingly labelled "Developers Guide". This is user documentation. It is probably where the Code API link _should_ point.

Why is that acceptable? Why can't Google find it? 

Seems like we need a documentation review for catkin. There are a lot of words, but it is very difficult for users to find what they need to know.

**Comment by dirk-thomas** [comment]
This is an API documentation which is intended for developers.

Should one of the catkin Wiki pages contain a user targeted description how to use nosetests? Absolutely!
I have create a ticket for that at ros/rosdistro#554

**Comment by jack-oquin** [comment]
With respect to catkin: 
- **developers** are people working on that package
- **users** are those generating catkin-compliant CMakeLists.txt files

The API documentation is for **users**. The confusing point is that they are "developing" some package that depends on catkin.

**Comment by tkruse** [comment]
Hi Jack,

the auto-generated API docs may also contain internal API that users should not use, and the apidocs are written with an audience of catkin developers in mind, not users. So that's why they are currently not part of the user documentation section.

Why Google cannot find it I don't know, that is annoying.

Also right now, on the page  http://ros.org/doc/groovy/api/catkin/html/dev_guide/
I see no link to the extracted cmake docs, even though the page exists.

So fixing the link and make google find the docs when searching for a macro should be fixed, IMO.

if you can come up with a nicer documentation structure / labelling that would be great, but a lot of this is about personal style and taste, leading to rather tiresome discussions about how documentation should be written, so don't expect much enthusiasm for a documentation review.

**Comment by jack-oquin** [comment]
OK

The purpose of a doc review is to give the writer user feedback on what needs to be explained, and what tasks people need to learn how to do. It is very hard for an expert in the topic to perceive things from that point of view.

**Comment by dirk-thomas** [comment]
Regarding the missing link: it looks like the nightly doc generator is not generating the cmake api file and the links to it correctly. I have ticketed that at https://github.com/ros-infrastructure/rosdoc_lite/issues/32

**Comment by jack-oquin** [comment]
Although this issue was closed a month ago, there is still no link from the catkin API page to the "Extracted CMake API Reference" page mentioned by @dirk-thomas.

I suggest that this issue be re-opened until it's actually fixed.

**Comment by jack-oquin** [comment]
See also: ros/catkin#410

**Comment by jack-oquin** [comment]
This page still exists: http://ros.org/doc/groovy/api/catkin/html/dev_guide/generated_cmake_api.html

But it says catkin 0.5.64, not the current release 0.5.65. 

Does it have to be generated by hand for each new catkin release? That would explain why it keeps getting disconnected from the top-level documentation. I suspect the missing links explain why Google can't find it.

Doing it again by hand is not an adequate fix. It'll just get lost again sooner or later.

**Comment by dirk-thomas** [comment]
Since the doc job will not be able to perform custom generations like that (in the foreseeable future) the generated_cmake_api.rst file is checked in the repo since 77446373ad23d43c5f5b494a4fcf98c86c2b7000.
This is a bit ugly as it requires manual regeneration to stay up-to-date when any api changes.

**Comment by jack-oquin** [comment]
This is the sort of "kicking the can down the road" solution I was hoping to avoid.

Other rosdoc_lite packages manage to include generated documentation without requiring extra manual tasks.

Why does that not work for catkin?

**Comment by dirk-thomas** [comment]
Please point me to another package with generates cmake api documentation via rosdos_lite and I will happily update the way catkin does it.

**Comment by jack-oquin** [comment]
This may not be a good example, but here's how I did it for Python:
- https://github.com/ros-geographic-info/unique_identifier/tree/master/unique_id
- http://www.ros.org/wiki/unique_id
- http://ros.org/doc/groovy/api/unique_id/html/python/

**Comment by dirk-thomas** [comment]
How does that example apply here? Sphinx knows how to extract API documentation from Python files. But in catkin we need to document CMake code.

**Comment by jack-oquin** [comment]
It does not directly. The point is that maybe the docs should be somewhere rosdoc_lite can process them automatically. Having comments in the CMake files is only useful for you and two or three others.

**Comment by dirk-thomas** [comment]
Well, we are documenting an API. Putting that into a separate rst file has the common drawback of getting out-of-sync with the implementation. So the documentation should stay within the code.

If we currently don't have a tool like doxygen/sphinx which allows us to perform the extraction automatically I don't see a better way to perform that. Hopefully tools will catch up and something like https://github.com/saschazelzer/CMakeDoxygenFilter will become generally available.

**Comment by jack-oquin** [comment]
This seems more important to me than it does to you. I suspect the reason is that you consider it "developer" documentation, while I am reporting a lack of adequate "user" documentation.

I don't care about developer documentation. Catkin developers will read the sources, anyway.

The real problem is that _users_ need catkin API docs. A user API should not mention non-public CMake functions or macros. Since it _is_ public, it should be stable, subject to review, and easy for Google to find. So, tight coupling with the implementation is not a problem. The implementation should not change those interfaces.

**Comment by dirk-thomas** [comment]
If additional user documentation is missing which goes beyond the API doc we can add that as additional rst files or in the wiki. If the API doc should be extended we can extend the comments in the code. Any pull requests on that are highly appreciated.

But the way the doc is generated is an implementation detail which nobody except me has to care about. Yes, it is inconvenient for me that I have to call the script every time when any API doc in cmake files change. But there is simply no tool to do the job fully automatic - autodoc would be great and would make it less manual effort - but implementing that is not on my todo-list. And since I have to maintain the API doc I will keep it together with the code. But this decision does not effect the content of the documentation - the content can be the same - no matter where it is coming from.
