### ISSUE TITLE
When auth with repo fails, catkin_package_version should not increment version nor repeat commit

### ISSUE THREAD

**Issue by 130s** [ros/catkin#407]
See [this question thread](http://answers.ros.org/question/60141/catkin_prepare_release-pushes-twice-wo-incrementing-tag/?answer=60349#post-id-60349). 

In my case, I might have failed auth once, then succeeds. That way the version in `package.xml` was 0.2.13 and `tag` in repo stayed 0.2.12 after one `catkin_package_version` execution. Also `commit` occurred as many as I failed auth + 1 success, with its msg remaining 0.2.12 for all commits.

**Comment by dirk-thomas** [comment]
The message remains the same since you have not run `catkin_prepare_release` again but just the commands printed from the initial invocation.

#417 will ensure for non-svn repositories that the user has push access (else it will not perform any action).

In case the pushing still fails with #417 `catkin_prepare_release` will output a message that the user has to manually invoke the push (instead of triggering another release).
