### ISSUE TITLE
catkin_pkg cannot be included in a catkin workspace

### ISSUE THREAD

**Issue by vrabaud** [ros/catkin#408]
e.g., I have src/catkin and src/ecto but when exporting path properply and doing my cmake ../src in build, I get an error due to the recursive behavior of catkin:
-- ~~  traversing 8 packages in topological order:
-- ~~  - ecto
-- ~~  - invalid_cmake (metapackage)
WARNING: The CMakeLists.txt of the metapackage 'invalid_cmake' contains non standard content. Use the content of the following file instead: /tmp/ecto_kitchen/build/catkin_generated/metapackages/invalid_cmake/CMakeLists.txt
-- ~~  - invalid_depends (metapackage)
-- ~~  - leftover_files (metapackage)
-- ~~  - no_buildtool_depend_catkin (metapackage)
-- ~~  - no_cmake (metapackage)
WARNING: The metapackage 'no_cmake' has no CMakeLists.txt. Please add one to the package source. You can use the following file: /tmp/ecto_kitchen/build/catkin_generated/metapackages/no_cmake/CMakeLists.txt
-- ~~  - no_metapackage_tag
-- ~~  - valid_metapackage (metapackage)
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CMake Error at catkin/cmake/catkin_workspace.cmake:88 (message):
  This workspace contains non-catkin packages in it, and catkin cannot build
  a non-homogeneous workspace without isolation.
Call Stack (most recent call first):
  CMakeLists.txt:48 (catkin_workspace)

-- Configuring incomplete, errors occurred!

That used to work. Then again, I have no idea whether that was a desired feature. Please close if not. Thx

**Comment by vrabaud** [comment]
BTW, the instructions that used to work are here:
http://plasmodic.github.io/ecto/

```
mkdir ecto_kitchen && cd ecto_kitchen
git clone http://github.com/ros/catkin.git
git clone http://github.com/ros-infrastructure/catkin_pkg.git
git clone http://github.com/plasmodic/ecto.git
ln -s catkin/cmake/toplevel.cmake CMakeLists.txt

export PYTHONPATH=`pwd`/catkin_pkg/src:$PYTHONPATH
mkdir build && cd build && cmake ../ && make
```

**Comment by dirk-thomas** [comment]
The instructions are not really good. Placing catkin_pkg in the source space of the workspace is not a good idea. You should simply not put catkin_pkg into the workspace (or place a CATKIN_IGNORE file in that folder).

Why is it failing now? Because catkin_pkg has recently added a couple of package.xml files for unit tests which specify a non-catkin build type. catkin_pkg itself is not a catkin package and therefore does not have a package.xml file in the root folder. So catkin finds the package.xml files in the test folder (which you actually don't want to build).

You could will a new issue against catkin_pkg that it could place a CATKIN_IGNORE file in the test folder. But I am not sure if it is a good idea to work around the issue that way. It would definitely be cleaner if you "fix" the ecto instructions.

**Comment by vrabaud** [comment]
ok, makes sense, it's not catkin's fault but catkin_pkg.
Is putting catkin in source space ok or is it also not recommended ?

**Comment by dirk-thomas** [comment]
Well I would say putting non-packages in the source space is the problem - any repo (which is not catkin related) might have a file coincidentally called package.xml which would brake.

catkin is a valid catkin package, so yes, you can put that into the source space. Usually you only want that if you bootstrap your system. As soon as you have any workspace build you already have catkin in the root workspace and don't need it again (but it does not harm, only overlaying the other catkin package).
