### ISSUE TITLE
set catkin_add_gtest workspace to source directory by default

### ISSUE THREAD

**Issue by ahendrix** [ros/catkin#416]
Currently, the test workspace for catkin_add_gtest is the binary output directory, which makes it difficult for compiled gtests to find the data files they need for testing, and requires any gtests ported over from the old system to be modified before they run properly.

I think the WORKING_DIRECTORY should default to ${PROJECT_SOURCE_DIR} so that the behavior describe in http://answers.ros.org/question/59779/data-files-for-catkin-gtest/ doesn't have to become common practice.

I've gone through the gtests in the desktop-full variant, and it doesn't look like any of them depend on the current behavior; none of them are calling open() with relative paths.

**Comment by dirk-thomas** [comment]
If you require a specific working directory (which is different from the current default) you should either specify the WORKING_DIRECTORY argument or pass the information where to find the test data to the test itself (e.g. by passing the path to the C++ compilation).

Changing the default path would only helps for your specific setup - in other cases (e.g. downloading test data) it would than be wrong the same way.

**Comment by jack-oquin** [comment]
Can you explain how to do that?

Does resolution using the ROS package path work correctly?

**Comment by dirk-thomas** [comment]
You have multiple options:
- Specify WORKING_DIRECTORY when registering the gtest. Than in the code you can use a path relative to that for loading data. The data could be in the source of the package or e.g. being downloaded into the build folder.
- Download the test data wherever you want and pass that path via a C++ PP variable into your code which than uses that compiled-in path.
- If the data is in a location where it can be found by the ROS tools at runtime (e.g. in the package share folder) the location can be discovered via rospkg / catkin.find_in_workspace.

**Comment by jack-oquin** [comment]
In other words, "no, resolution using the ROS package path does _not_ work". Sounds like none of this works with plain rostest, either.

How do I pass the path name of a test file with a ROS parameter?

**Comment by dirk-thomas** [comment]
As mentioned in the last post in option 3 - you can use rospkg.get_path / catkin.find_in_workspace to find your resources. So "yes, resolution using the ROS package path does work".

rospkg.get_path will only resolve files from the source folder of the package as it is not aware of any build/devel space and FHS. catkin.find_in_workspace lets you search in devel space as well as in source space. If you want to find things in build space you can use option one (where as the working directory points by default to the package's build dir).

**Comment by jack-oquin** [comment]
So, you have to install it in `${CATKIN_PACKAGE_SHARE_DESTINATION}`? That's not very reasonable for test data.

None of this helps solve the problems of using `download_test_data()` with `rostest`:
- http://answers.ros.org/question/63189/how-do-i-use-download_test_data/

If I open a new issue for that, will you just close it, too?

**Comment by dirk-thomas** [comment]
I have closed this specific issue regarding `catkin_add_gtest()` since I described feasible ways how to achieve the described goals. The ros answer you refer to is significantly different from this issue - it uses rostest and therefore a roslaunch file for the test.

The roslaunch commands are (even with the enhancement described in ros/ros_comm#228) only able to find files in source/devel/install space. Files from build space can (and should) not be resolvable by roslaunch since it should not even know about the build process and layout.

So this leaves the following options for that case:
- either download the files into the source space of the package (as it was with rosbuild), files are than resolved with $(find), $(find-share) and $(find-share-source)
- or download the files into the devel space of the package (which does not imply to install these files), files are than resolved with $(find), $(find-share) and $(find-share-devel)
- or download the files into the build space or a temporary location (where I think they belong), for this the location must be made available for the test. It is currently not possible to pass arguments to rostest launch files. Other packages (e.g. rosbag migrations test) do this by embedding the location of the test data into the tests (using CMake configure_file).

If you ask for my personal opinion: all three options are suboptimal. If we ever want to enable running tests after having installed the code all three approaches are insufficient. For that case the test should be able to download its test data when its getting executed.

Please feel free to open a new ticket describing this use case. It would be great if you could also propose a way how this could be implemented in that ticket.

**Comment by jack-oquin** [comment]
Thanks, Dirk. 

Sorry for getting grouchy. It's been really frustrating converting that package to catkin.

The only solution I can think of is storing the test data in /tmp/PACKAGENAME/, so it can be referenced as an absolute path name. That will probably work, but it sucks, and I would hate to document that as a "best practice".

Where should such a ticket be opened?

**Comment by dirk-thomas** [comment]
The catkin issue tracker is fine.
