### ISSUE TITLE
Python script name backward compatibility

### ISSUE THREAD

**Issue by oars** [ros/catkin#434]
I just began migrating some projects we had running on fuerte and after some debugging found out that the reason my project was not working was because of the name of my python scripts.

Many of them would have the same name as the package, but would still work under fuerte. With catkin the python path now includes "~/catkin_ws/src/< pkg_name >/scripts/" and so an import of the type: from pkg_name.msg import < msg > will result in the script importing itself.

I don't know if changing the sys.path order to have the devel/lib/... path located before the  src/< pkg_name >/scripts/ is the right thing to do. Otherwise a simple warning in the tutorials and the migration wiki would suffice.

To reproduce this error one could use the sample listener.py and talker.py from the wiki tutorial then:
- Create a msg type like the Num.msg example
- Import the message type in the listener.py
- Rename listener.py to beginner_tutorials.py
- `rosrun beginner_tutorials beginner_tutorials.py`

**Comment by dirk-thomas** [comment]
catkin does not add `~/catkin_ws/src/< pkg_name >/scripts/` to the PYTHONPATH.

It only looks for packages you specify in the setup.py file in the referenced source location. So if you have a package foo under src and `import foo` will look in `~/catkin_ws/src/foo` (but nothing with scripts).

The problem you are facing is that a Python file and a Python package have a naming collision. Beside renaming you could also fix the import in your script by forcing an absolute import (see `from __future__ import absolute_import` in PEP 328 http://www.python.org/dev/peps/pep-0328/) rather than self-importing itself due to relatively resolving the package name.

If you have a specific suggestion which tutorial to change and especially how please either comment here or consider contributing to the wiki directly.

**Comment by oars** [comment]
I think I mostly understand what you are saying. I guess it was more of a fluke that things worked in fuerte due to the placement of the generated msg modules within the src directory. 

I'll retrace my steps by following the wiki and see where/if a warning of some sort would make sense along the way.

Thank you
