### ISSUE TITLE
Trouble with Catkin: Compiling node and generating messages in same package.

### ISSUE THREAD

**Issue by raptort3000** [ros/catkin#435]
Please see the following link for info on the bug: http://answers.ros.org/question/64448/trouble-with-catkin-compiling-node-and-generating-messages-in-same-package/

**Comment by dirk-thomas** [comment]
You might consider providing a repository which people can just checkout and try the code from your question posted on ROS answers. May be that help to figure out where the issue is.

This is not a catkin issue since it obviously works for numerous existing ROS packages. Nevertheless if it would be a general issue it would be for the package genmsg and not catkin.

**Comment by wjwwood** [comment]
We need either your code to test with, or a simple toy problem which narrows down the the problem in a reproducible way. If you can provide either of those and we can reproduce it, then we will reopen this issue.

**Comment by jbohren** [comment]
I don't think it's something that can be tested with example code, or test-driven development. The test is "can a user easily build messages when they want to" In this case, the test failed, and it points to a documentation and/or usability issue.

**Comment by dirk-thomas** [comment]
The documentation clearly states how to specify the necessary dependencies between the library target and the the message generation target. Since nobody can spot an obvious issue in the posted code the best way is to post a ready-to-use example - either a simple test case which reproduces it or the full code the user is experiencing the problem with.

**Comment by wjwwood** [comment]
@jbohren This is not a usability thing, in his question of ROS answers he is doing what the documentation prescribes and I don't see any thing wrong with his CMakeLists.txt, so it must be some other thing he has in his environment or something else we are missing. For us to proceed in helping him we need a reproducible case.

**Comment by tkruse** [comment]
It may still be an issue of usability if error reporting is insufficient. But in any case, the error must be reproducible to decide whether some valiudation and/or error message needs improving.

**Comment by raptort3000** [comment]
Hi guys,

Here is the repository with the code that is producing this error: https://github.com/raptort3000/ublox_catkin

git clone https://github.com/raptort3000/ublox_catkin.git

**Comment by wjwwood** [comment]
I addressed the issue in a pull request:

https://github.com/raptort3000/ublox_catkin/pull/1

**Comment by wjwwood** [comment]
I don't see a reason to open this issue again unless someone has a concrete idea on how to improve the error detection and handling here. Even then I think a new issue/pull-request might be appropriate.
