### ISSUE TITLE
ROS_PACKAGE_PATH is sometimes backwards

### ISSUE THREAD

**Issue by hershwg** [ros/catkin#455]
I don't yet know how to reproduce this, but I thought someone might have ideas about what would cause it.

Some of our users complain that sometimes when they build a big catkin project, their ROS_PACKAGE_PATH ends up backwards, like:

```
/opt/ros/groovy/share:/opt/ros/groovy/stacks:/home/myaccount/myproject/src
```

This causes lots of trouble, since myproject is now an _underlay_ of ros groovy instead of an _overlay_.

Looking in the project's devel/_setup_util.py includes this line:

```
CMAKE_PREFIX_PATH = '/opt/ros/groovy;/home/myaccount/myproject/devel;/home/myaccount/myproject/devel'.split(';')
```

I did not set up this project dir initially, so I don't know what the circumstances were.  Obviously it is possible that someone explicitly set the CMAKE_PREFIX_PATH to that backwards path and then ran catkin_make, but I doubt it.

Advice appreciated.

**Comment by dirk-thomas** [comment]
A custom CMAKE_PREFIX_PATH with the wrong order in the first place is the only reasonable explanation.

Please provide information about the environment _before_ the workspace was created and the exact parameters of the initial catkin_make command. Alternatively any command sequence which reproducible leads to the described result.

**Comment by tlau** [comment]
We have this process scripted on our turtlebots (including the catkin_make command which produces this result). I'll try doing a clean build tonight, starting from scratch, with no CMAKE_PREFIX_PATH in the environment, and report back tomorrow.

**Comment by tlau** [comment]
OK, after a clean build unfortunately I can't reproduce the problem.  I'll keep monitoring it and see if I can come up with a reproducible test case when it happens again.

**Comment by tlau** [comment]
Aha, I was able to reproduce it on my desktop (which builds a lot faster than turtlebots).  I isolated the problem to building with the `-DCMAKE_BUILD_TYPE=RelWithDebInfo` flag. This leaves the ROS_PACKAGE_PATH in the wrong order, whereas running `catkin_make` without that argument generates the correct path ordering.

My understanding is we were using that flag on turtlebots to make optimized builds rather than debug builds because they need all the optimization they can get.

**Comment by tlau** [comment]
Unfortunately although I did see it happen several times, I'm unable to consistently reproduce it using a known combination of unsetting ROS\* envvars, running catkin_make with and without that flag, and using script to capture the output so you guys can see it.  Grr.

**Comment by jonbinney** [comment]
@tlau, have you ever seen this outside of a tmux session? Maybe tmux is doing something funky with environment variables?

**Comment by tlau** [comment]
I don't know, I never build outside of tmux!  What a strange thought -- I would not expect tmux to muck with envvars, but it's a possibility.

I've seen this crop up several times since we first reported it, but every time I try to rerun catkin_make to reproduce the problem, it corrects itself. I still have no idea what could be causing it.

**Comment by jonbinney** [comment]
I think that tmux does some funny stuff because it has to reconcile environment variables from several sources:
- the pane you were in before you created the current pane
- the parent process when you created the tmux session
- the parent process when you attached to the tmux sessions

Not sure what logic it uses for this.

**Comment by jonbinney** [comment]
@baalexander and @ablasdel think they've narrowed it down to the case where your .bashrc sources some ros stuff, and then you run tmux (so the parent process has ROS environment vars), and then you do catkin_make inside of tmux.

Also it looks like the turtlebots are sourcing /opt/ros/groovy/setup.sh twice, once through some scripts in /etc, and again directly:

```
. /etc/ros/setup.bash
source /opt/ros/groovy/setup.bash
```

After commenting these out and starting a new tmux session, this problem went away.

**Comment by jonbinney** [comment]
I think this issue can probably be closed, since circumstantial evidence points to it not being a catkin bug.

**Comment by tlau** [comment]
Very cool. Good find, @baalexander and @ablasdel. It'd be nice to understand how it's happening though.

**Comment by jonbinney** [comment]
I think figuring out what exactly is happening would involve digging into how tmux works

**Comment by tlau** [comment]
Well, I meant at least understanding what differences exist in the environment variables under the two conditions so we know what is getting passed to catkin_make that causes it to do the wrong thing. Then at least we'd know what to check for, other than "don't run this exact series of commands".

**Comment by jonbinney** [comment]
I just ran into this problem again, and using a console outside of tmux fixed it. Very frustrating. Still don't have a reliable way to reproduce the problem, unfortunately. It seems to be non-deterministic somehow.

**Comment by rubenalvesbcn** [comment]
I had the same problem and the reason was because I had ros installed on `/opt/ros/` and also had the code of ROS ([from source](http://wiki.ros.org/kinetic/Installation/Source)) on my `~/catkin_ws/src`.

After remove "ros" from `~/catkin_ws/src`, run `catkin_make` again on `~/catkin_ws` and open a new terminal, everything went fine.

So, if anyone see this problem again, maybe is because you have two ROS Versions.
