### ISSUE TITLE
documentation: recommend "if (CATKIN_ENABLE_TESTING)" for unit tests

### ISSUE THREAD

**Issue by jack-oquin** [ros/catkin#467]

**Comment by dirk-thomas** [comment]
I wanted to push this doc out so went ahead and committed some changes. Please feel free to provide more feedback and enhancements to the docs.

**Comment by jack-oquin** [comment]
Apparently, you chose to throw away some of my work.

Is there some explanation for what you changed, and why?

**Comment by dirk-thomas** [comment]
If you refer to commit jack-oquin/catkin@7fe6665b0754ae8bca6d7824272c62aa2bd69993 I did not "throw away" any of your work. I made changes to exactly the same files and locations (basically to all test-related commands). But in some cases I added a more descriptive text since I thought it would be necessary to be more verbose (e.g. in the index file as well as for rostests). Regarding the reformatting of the headlines: it was not obvious for my why this was done and therefore I did not included this in my patch.

Please feel free to provide feedback / a pull request on anything which you consider being "lost".
