### ISSUE TITLE
conflict between same target names from different packages

### ISSUE THREAD

**Issue by piyushk** [ros/catkin#477]
I just tried to compile gazebo_ros_pkgs and hokuyo_node in the same ws. gazebo_plugins contains a target called hokuyo_node, which conflicts with the one present in the hokuyo_node package:

```
CMake Error at hokuyo_node/CMakeLists.txt:42 (add_executable):
  add_executable cannot create target "hokuyo_node" because another target
  with the same name already exists.  The existing target is an executable
  created in source directory
  "/home/bwi/catkin_ws/src/gazebo_ros_pkgs/gazebo_plugins".  See
  documentation for policy CMP0002 for more details.
```

I am not sure if this is a regression or not. I believe it should be allowed.

**Comment by dirk-thomas** [comment]
For `catkin_make` all packages share the same namespace regarding target names since the whole building uses a single CMake invocation. Please fill a ticket against https://github.com/ros-simulation/gazebo_ros_pkgs.

In the meantime you can use `catkin_make_isolated` which will run CMake on each package separately (but will be significantly slower).

**Comment by tfoote** [comment]
The standard is for all targets in a catkin package to use `${PROJECT_NAME}` as a prefix. Where `${PROJECT_NAME}` is set at the top to be the name of the package.  This will avoid all conflicts as package are already a flat namespace.
