### ISSUE TITLE
catkin_make install vs catkin_make_isolate --install

### ISSUE THREAD

**Issue by jihoonl** [ros/catkin#481]
I just noticed that creating install space between catkin_make and catkin_make_isolate

> catkin_make install

whereas 

> catkin_make_isolate --install

Should they be the same?

**Comment by wjwwood** [comment]
They cannot be the same because of the way `catkin_make_isolated` works.

`catkin_make` is passing the `install` argument as a target name to `make`. `catkin_make_isolated` has to do special things when dealing with non-catkin packages, so it cannot just pass the make target along like that. Therefore, there is an `--install` option which does the right thing for all catkin and non-catkin packages in the workspace.
