### ISSUE TITLE
python2.6 compatibility errors

### ISSUE THREAD

**Issue by tkruse** [ros/catkin#518]
Not sure if anyone still cares about python2.6 (default with lucid), but it seems in few places catkinb code uses python2.7 features:

```
File "src/catkin/bin/catkin_make", line 102
  packages_by_name = {p.name: path for path, p in packages.iteritems()}
```

and

```
File "src/catkin/bin/catkin_make", line 15, in <module>
  from catkin.builder import cmake_input_changed
File "src/catkin/bin/../python/catkin/builder.py", line 698
  packages_by_name = {p.name: path for path, p in packages.iteritems()}
```

and

```
File "/pr/1/tkruse/work/groovy/build/catkin_generated/generate_cached_setup.py", line 21, in <module>
  code = generate_environment_script('/pr/1/tkruse/work/groovy/devel/env.sh')
File "/pr/1/tkruse/work/groovy/src/catkin/cmake/../python/catkin/environment_cache.py", line 61, in generate_environment_script
  output = subprocess.check_output([env_script, sys.executable, '-c', python_code])
AttributeError: 'module' object has no attribute 'check_output'
```

IMHO, staying 2.6 compatible is worth more than saving 2-3 lines of code for now.

**Comment by dirk-thomas** [comment]
Since the current development branch of catkin does only work for Groovy and Hydro and those distributions do neither support Lucid nor Python 2.6 (see http://ros.org/reps/rep-0003.html#groovy-galapagos-oct-2012) I don't think it is worth keeping Python 2.6 compatibility.

Especially with the goal of making the whole code base compatible with Python 3.x for the next ROS distribtion it would be even more effort to also keep 2.6 compatibility.

**Comment by tkruse** [comment]
Indeed maybe it is silly to think of catkin as useful software outside the ROS context.
ROS users trying older platforms still can patch catkin themselves if need be.
