### ISSUE TITLE
Outdated wiki information about ROS concepts

### ISSUE THREAD

**Issue by tkruse** [ros/catkin#540]
Catkin is not mentioned, nor are metapackages:
- http://wiki.ros.org/ROS/Concepts
- http://wiki.ros.org/Packages
- http://wiki.ros.org/Stacks
- http://wiki.ros.org/Manifest
- http://wiki.ros.org/Stack%20Manifest

**Comment by dirk-thomas** [comment]
Please feel free to contribute to the ROS wiki or propose specific changes if need is on the mailing list / this ticket.

**Comment by wjwwood** [comment]
I duplicated into the `rosbuild` namepsace all of the largely rosbuild specific pages for the ROS Overview (Includes the /ROS/Concepts page) and all of the elements in the "ROS Filesystem Concepts" menu group. Entry point:

http://wiki.ros.org/rosbuild/ROS/StartGuide

Now we can edit the wiki pages @tkruse mentioned without worrying about catkin/rosbuild buttons, and simply refer to the rosbuild specific version of the overview.

For pages where only small snippets are catkin/rosbuild specific I think we should continue to use the buttons.

I had to duplicate a few pages which were not otherwise rosbuild specific to make sure that links pointed to rosbuild versions of the pages. I couldn't find a way to use relative links to prevent the duplication.

**Comment by wjwwood** [comment]
Done. I did the bulk of the refactoring, but given the amount of information there I am sure I missed things. It should be considerably better though.

**Comment by dirk-thomas** [comment]
Thank you @wjwwood for looking into it immediately.

@tkruse if you find missing / incomplete parts please either update the wiki page directly if you feel comfortable or comment on this ticket with specific pointers.

**Comment by tkruse** [comment]
thanks, William
