### ISSUE TITLE
Add a way to enable pre and post package configure hooks

### ISSUE THREAD

**Issue by tfoote** [ros/catkin#543]
These hooks could be used by catkin_lint to enable debugging of all variables changed between configuration of each package. 

These hooks could be used to print out the delta of all variables changed during a package configuration. This will allow detection of side effecting changes.

Ala http://stackoverflow.com/questions/9298278/cmake-print-out-all-accessible-variables-in-a-script

This is something that could then be hooked into a linter and debugging display.

**Comment by dirk-thomas** [comment]
The pre and post hooks could wrap the following line in the `catkin_workspace` function: https://github.com/ros/catkin/blob/groovy-devel/cmake/catkin_workspace.cmake#L109

E.g. all variable (before and after each package) could be written to a file like this:

```
# pre hook
file(APPEND cmake_vars.log "Before package ${PROJECT_NAME}") 
get_cmake_property(_vars VARIABLES)
foreach(_var ${_vars})
    file(APPEND cmake_vars.log "${_var}=${${_var}}")
endforeach()

add_subdirectory(${path})

# post hook
file(APPEND cmake_vars.log "After package ${PROJECT_NAME}") 
get_cmake_property(_vars VARIABLES)
foreach(_var ${_vars})
    file(APPEND cmake_vars.log "${_var}=${${_var}}")
endforeach()
```

@mikepurvis @jack-oquin Please give this a try when looking into linting. If this kind of information is useful I could add these generic hooks so that the linter can integrate this logic into the workspace iteration.

**Comment by mikepurvis** [comment]
For my clarification, this is solely to do with a catkin linter (#153), not the general problem of linting various sources. Is that correct?

**Comment by dirk-thomas** [comment]
Yes, linting catkin CMake logic.

**Comment by jbohren** [comment]
@tfoote Would the pre- and post-config hook mechanism you describe enable any package to export code which runs before and after the configuration of any package depending on it, or something else?

**Comment by dirk-thomas** [comment]
No, the idea of these hooks is that you can pass a pre/post-hook handler (a cmake file) to the invocation of CMake. That code is than run in a workspace before/after each package. That way a lint-application can pass in hooks which e.g. logs the current variable in cmake for later analysis.

**Comment by mikepurvis** [comment]
FWIW, I don't think we intend to put the catkin linter in the roslint package—at the very most, we would incubate it there for a short while. A catkin linter should either be provided by/with catkin itself, or as a standalone package.

**Comment by dirk-thomas** [comment]
Agreed. If someone will work on catkin lint and would use such hooks as described in this ticket I am fine adding them as a feature to catkin.

Until then adding them seems to be not necessary - therefore marking this ticket with the milestone _untargeted_.

**Comment by tkruse** [comment]
Note I suggested in #265 not just to report changes in global vars, but to revert those changes before moving on to a next package. Maybe it's still not a great idea, but I thought I could still throw it in.

**Comment by mikepurvis** [comment]
@tkruse I think I may have got bitten by a workspace cross-talk issue the other night, too, and it's miserable to debug. Relying on every package to use an opt-in system like roslint doesn't seem like a realistic way to handle that particular problem.

What would be the overhead to just having catkin_make make these checks automatically, same as how it yells at you for trying to find_package() something you didn't `<build_depend>` on? The ideal would be, as you say, to actually revert the change so that the build proceeds, but post a warning for the user that the package in question muddied a "protected" global CMake/catkin variable, and to please contact the package maintainer about it.

An --unsafe or --quick flag to catkin_make could disable this behaviour when you're running a large build of things you're fairly sure are safe.

**Comment by tkruse** [comment]
@mikepurvis: Please consider sharing your debugging misery here: #539, to collect all reports of debugging frustration attributed to lack of isolation in catkin. catkin will not be changed unless enough people actually report their problems. The main question being whether catkin_make saves time or wastes time, by being faster but more vulnerable.

Regarding opt-in: Unless I am mistaken, @dirk-thomas would integrate a check for suspicious global-var changes into the process started by catkin_make, so that bit at least would not be an opt-in system. Other catkin-lint checks might still be opt-in though.

Regarding reverting variables:
In general, global variable changes in cmake are not worthy a warning, they are normal occurences, so general warnings would not be useful.
The problem with reverting variable values is that we don't know what else could break in any attempt of doing so, as @dirk-thomas hinted at in #265. Possibly, once we get the output from the configure hooks suggested in this thread, we might see that reverting variables can be safely done (We'd have a better basis for discussion).

**Comment by tfoote** [comment]
@tkruse what these hooks would enable wouldn't be an opt-in system that you enable per package. It would be that you can invoke cmake on the whole workspace with the debugging hooks turned on, probably via a helper wrapper script which would parse the output files. 

@mikepurvis If you do believe that CATKIN_IGNOREs are not being honored fully or you can repeatedly reproduce the issue compiling on different platforms, please file your specific issue as a separate ticket.  That way we can make sure to track and make sure that it doesn't get lost.

**Comment by dirk-thomas** [comment]
I will mark this ticket as `wontfix` and close it since there is no use case yet where this functionality is used. As soon as someone works on a _catkin lint_ it would be feasible to implement the proposed hooks and this ticket can be reopened.
