### ISSUE TITLE
catkin_prepare_release: adjust to svn 1.7+ when releasing subtrees of a repo

### ISSUE THREAD

**Issue by 130s** [ros/catkin#556]
Starting from version 1.7, which comes with `Ubuntu Raring`, `svn` stopped generating `.svn` files in all folders.
http://subversion.apache.org/docs/release-notes/1.7.html#wc-ng

With projects downloaded by `svn` 1.7+ where ROS packages are placed in the subfolders (the case already handled in https://github.com/ros/catkin/issues/513), `catkin_prepare_release` fails as follows:

```
$ cd %ROSPKG_SRCDIR_TOP%
$ catkin_prepare_release 
Prepare the source repository for a release.
Could not determine repository type of '.'
```

**Comment by dirk-thomas** [comment]
If you are in the root of your working copy the command should work fine. None of the other VCS types allows you to invoke the command in a subfolder of the working copy.

This is only relevant if you are going to release a subtree of a SVN repository. Therefore I will mark this ticket with the milestone _untargeted_ since it is not a feature the maintainers will work on. Please consider providing a patch if you want that use case to be supported.

**Comment by 130s** [comment]
I'm fine with setting this untargetted. Just as a record, there are ROS `svn` repositories that place packages in sub folders. A few of them are [listed here](https://github.com/ros/catkin/issues/513#issuecomment-24992051).

**Comment by dirk-thomas** [comment]
I just took a brief look to the referenced repos but none of them seems to contain catkin packages.

**Comment by 130s** [comment]
Ah, you're right! Those repos were the last stronghold for us to stick to place packages in subfolders. Now I'll suggest my team to change our long-lasting repository structure to more common way.

You can close this ticket if that's better.

**Comment by dirk-thomas** [comment]
I will go ahead and close this ticket since there seems to be no interest in this feature.
