### ISSUE TITLE
problem sourcing setup.sh

### ISSUE THREAD

**Issue by hugomatic** [ros/catkin#561]
This is what I get with setup.sh:

ubuntu@ip-10-217-153-196:~/cloudsim$ . /opt/ros/groovy/setup.sh
close failed in file object destructor:
sys.excepthook is missing
lost sys.stderr
-bash: [: 0: unary operator expected

And this is setup.bash:

ubuntu@ip-10-217-153-196:~/cloudsim$ . /opt/ros/groovy/setup.bash
close failed in file object destructor:
sys.excepthook is missing
lost sys.stderr

**Comment by dirk-thomas** [comment]
It looks like that the executed `_setup_util.py` script fails and later the shell script does not have the variables set it expects. But I need more information in order to figure out what the problem in your case is.

Can you please invoke the python script manually (in the same way as it is called by the `setup.sh` file) and post the result (hopefully an error message / stacktrace)?

**Comment by hugomatic** [comment]
I did not expect setup.sh to create any temporary files. The setup.sh was probably failing because the disk got full.

**Comment by dirk-thomas** [comment]
That fits the above description perfectly. If the disk is full `_setup_util.py` fails to pipe the output to the temporary file. Python fails to signal the error before the script is already shutting down. which leads to the `sys.excepthook is missing` (http://bugs.python.org/issue11380).

The solution is:
- actually check the return code of the `_setup_util.py` invocation
- update `_setup_util.py` to explicitly flush stdout at the end as well as catch a broken pipe exception
