### ISSUE TITLE
executable can not be named test

### ISSUE THREAD

**Issue by LucidOne** [ros/catkin#644]
`add_executable(test src/test.cpp)`
Fails mysteriously

`add_executable(this_test src/test.cpp)`
Works

I am not sure if this is an error or if it should just throw a warning.

**Comment by dirk-thomas** [comment]
Since CMake already generates a built-in `test` target for CTest I don't think it is valid to use the same target name.

**Comment by LucidOne** [comment]
Can the add_executable macro throw an error if you try `add_executable(test src/test.cpp)`

**Comment by dirk-thomas** [comment]
No, this is a pure CMake function. `catkin` has nothing to do with it.

**Comment by wjwwood** [comment]
@LucidOne unfortunately, we don't control this macro.

For better or worse we've tried to avoid wrapping CMake calls where possible, this makes it more conventional CMake and less intrusive, but it also means we have less opportunity to catch errors like this one.

> > add_executable(test src/test.cpp)
> 
> Fails mysteriously

In my experience it fails in a very specific way, it tells you that a target this that name already exists, but if you got something different, maybe you should post what you got?

**Comment by dirk-thomas** [comment]
Since it is a target generated later I don't think CMake gives you the same message as for colliding target names.

@LucidOne You can still create a test executable - you just have to name the target differently:

```
add_executable(my_test src/test.cpp)
set_target_properties(my_test PROPERTIES OUTPUT_NAME test)
```

I will close this ticket as "wont fix" since this is standard CMake behavior. Please feel free to post your exact error message as @wjwwood suggested as a reference for other people finding this ticket in the future.
