### ISSUE TITLE
Improve rollback of environment changes

### ISSUE THREAD

**Issue by dirk-thomas** [ros/catkin#648]
We would like to be able to rollback:
- changes done by environment hooks
- changes from workspaces which have been deleted after being sourced

Please consider proposing approaches for this and state their pros / cons.

**Comment by jbohren** [comment]
In order to enable people to easily roll-back environment hooks, I think we should define a few classes of environment modifications which env-hooks tend to define along with the assumptions about "good behavior" for these hooks. Then for certain types of env-hooks, catkin might simplify the rollback process by providing scripts to process environment variables for standard patterns. Each pattern can include watchdogs which can compare the environments before and after running a given hook and raise a warning if something dangerous is happening.
- Mode environment variables
  - Single-values which cannot be appended to 
  - **env-hook:** defines a previously-undefined environment variable
  - **env-release:** deletes the environment variable  
  - **env-watchdog:** raises a warning if an env-hook redefines an existing environment variable
- PATH-type environment variables
  - Token-delimited list of paths in a filesystem
  - **env-hook:** prepends entries contained in run-space
  - **env-release:** removes entries contained in run-space  
  - **env-watchdog:** raises a warning if a PATH-type variable is unset or if entries are removed which are not in the run-space
- Shell functions
  - **env-hook:** defines a previously-undefined shell function
  - **env-release:** deletes shell function
  - **env-watchdog:** raises a warning if an env-hook redefines an existing shell function

---

In the event that a workspace is deleted and then _any_ catkin setup file is loaded before the deleted workspace has been rolled back, that setup file should detect that a workspace has been deleted (missing entry in `$CMAKE_PREFIX_PATH` or something) and issue a warning like the following:

```
WARNING: A Catkin setup file is attempting to clean up the environment set by the Catkin
workspace located at /path/to/the/deleted/ws, but this workspace has already been deleted.

It is advised that you create a new shell with a clean environment and re-run:
  source path/to/other/ws/you/are/trying/to/source/devel/setup.bash
```

We can implement the above warning very soon without having to design a complex way of making env-rollback work if a workspace has been removed. Later on if we determine a way to make that more robust, we can add it in.

If we want to avoid this printing out when a workspace had _no_ env-hooks, then maybe this could use an environment variable other than `$CMAKE_PREFIX_PATH` like `$CATKIN_ENV_STACK` or `$CATKIN_RUN_SPACE_STACK` or something like that.

**Comment by NikolausDemmel** [comment]
> We can implement the above warning very soon without having to design a complex way of making env-rollback work if a workspace has been removed. Later on if we determine a way to make that more robust, we can add it in.

+1

One way to eventually implement the rollback even with deleted workspaces would be a mechanism where the environment hooks are required to store the necessary rollback information in the environment itself. For the known patterns mentioned above this could be achieved by appending the set environment variable names to a list of variable names for each known pattern, e.g. `CATKIN_ENV_HOOK_PLAIN_VARIABLES`, `CATKIN_ENV_HOOK_PATH_VARIABLES`, `CATKIN_ENV_HOOK_FUNCTIONS`.

Pro: Fairly simple, works with many of the existing variables; new patterns could be defined by plugins to catkin;

Con: Even more env variables; cannot support all possible patterns out of the box; all env hooks need to be rewritten; hard to enforce (maybe there could be something like env-hook-lint)

An alternative idea would be a special environment variable `CATKIN_ENV_HOOK_UNROLL_FUNCTIONS`, where each env hook appends one or more shell function names that together roll back the env_hook's effect (including unsetting the shell function itself).

Pro: Flexible; "just" one additional env varibale; tools to create appropriate functions for the known patterns above can be provided

Con: More state in the environment (env variable, shell functions); all env hooks need to be rewritten; hard to enforce; maybe more fragile than other approaches (if the unroll function fails but has already removed itself, we cannot run it again);

**Comment by dirk-thomas** [comment]
What about the following approach to cover at least "separate" environment variable:

Before sourcing the environment hooks in https://github.com/ros/catkin/blob/cf32d594b9e541363b4141b099b4920b437a0ab2/cmake/templates/setup.sh.in#L72 a list of environment variable is stored. After sourcing all hooks the list of environment variables is fetched again. The name of any "new" environment variable is appended to e.g. `_CATKIN_UNSET_ENVIRONMENT_VARIABLES_ON_ROLLBACK`. Earlier in the setup file we loop over all names in this variable and unset those variables (and clear the rollback variable).

That would cover a lot of the cases but only require minimal effort to implement it. And it does not require to change any environment hook.

**Comment by NikolausDemmel** [comment]
Aren't the variables that are newly set and didn't exist before the least critical anyway, since they would be overwritten when sourcing a new `setup.bash` in a shell with another result space soruced?

While the cost of implementing this is low and a big plus is that no env hooks have to change, the cost of possibly being confusing when only doing this without a concept for other environment variables is maybe not so low.

**Comment by dirk-thomas** [comment]
I will mark this with the milestone `untargeted` since obviously nobody is currently willing to implement any of the ideas.

**Comment by asmodehn** [comment]
I am probably missing something here, so excuse my naive approach, but why not starting a new shell for each workspace setup ?
rolling back is then just exiting that shell. An environment variable is a configuration for a shell process after all.

One can setup a stack of workspace and rollback, using the stack of shell processes. and passing variable down that shell stack can be done with usual shell commands (export).

This will reuse shell features without implementing anything complex, and will also have expected behavior from users...

The only downside I can see is that one may want to rollback a workspace deep down in the stack, or a single env-hook, but keeps its current shell changes.

However I think that, being certain that a "cleanup action" will cleanup everything I want in a predictable and familiar way, is the most important.

**Comment by dirk-thomas** [comment]
A nested shell is visually distinguishable by a user and therefore not obvious. But you can perform that manually before sourcing a setup file if you like to.

**Comment by dirk-thomas** [comment]
Since this is unlikely to ever get implemented I will close this ticket for now.
