### ISSUE TITLE
".catkin" marker file can be overwritten if two catkin instances are running with a shared develspace

### ISSUE THREAD

**Issue by jbohren** [ros/catkin#670]
For example, when using `catkin build` from [catkin_tools](http://github.com/catkin/catkin_tools), there is a chance that some package source directories will not be listed in the `.catkin` file. If one package A writes it after another package B has read it, but before B has written to it, then A's modifications will be overwritten when B writes to it. This, in turn, means that they will not enter into `$ROS_PACKAGE_PATH`.

This was formerly discovered and discussed in catkin/catkin_tools#77.

**Comment by dirk-thomas** [comment]
This requires to make the modification to file an atomic operation. Please consider to provide a pull request for this.

As a side note: https://github.com/ros/catkin/blob/indigo-devel/cmake/atomic_configure_file.cmake does something similar but since it does only overwrite the file (rather then extending it) the approach will not work for this case.

**Comment by dirk-thomas** [comment]
I will close this with #671 merged and also being released in all distros.

The tickets (#674, #675) track separate enhancements.
