### ISSUE TITLE
Create thread-safe storage of source-space paths

### ISSUE THREAD

**Issue by jbohren** [ros/catkin#674]
Currently, as described in #670, when multiple catkin cmake processes are running with a merged develspace, they each want to modify `devel/.catkin` in order to store the sourcespace paths for each package. This information is used to build PATH-like variables like `$ROS_PACKAGE_PATH`.

If a parallel-safety flag is set, as proposed in  #675, then we could generate this file with a top-level tool like `catkin build`.

**Comment by dirk-thomas** [comment]
Please consider to provide a pull request for this.

**Comment by dirk-thomas** [comment]
I assume `catkin_tools` addresses the need in its own way and this ticket can be closed?

**Comment by jbohren** [comment]
> I assume `catkin_tools` addresses the need in its own way and this ticket can be closed?

No, `catkin_tools` doesn't address this.

**Comment by dirk-thomas** [comment]
I will close this issue for now since it is unlikely that anyony is working on this in the future and it is unclear how this could be addressed in `catkin` itself.

Imo the build tool should avoid performing tasks in parallel which access the same files, e.g. by passing `CATKIN_BUILD_BINARY_PACKAGE` and generating these files itself.
