### ISSUE TITLE
explicitly add --as-needed to linking flags

### ISSUE THREAD

**Issue by v4hn** [ros/catkin#680]
This addresses linking errors/heavy overlinking with rosbuild as well as with catkin
on non-Debian systems.

Read the full story at answers.ros.org:
http://answers.ros.org/question/138766/why-is-as-needed-not-explicitly-set-for-ros-workspaces/

**Comment by dirk-thomas** [comment]
I would rather recommend gentoo users to set their linker flags accordingly then make catkin (or catkin_make) aware of these platform specific differences.

**Comment by v4hn** [comment]
On Tue, Dec 09, 2014 at 02:06:01PM -0800, Dirk Thomas wrote:

> I would rather recommend gentoo users to set their linker flags accordingly then make catkin (or catkin_make) aware of these platform specific differences.

Hey Dirk, thanks for your comment.

First off, this is not a matter of any particular distribution.
If anything, this is about the idea of some major distributions to change linker _sources_
to make the default of ld --as-needed when the upstream sources specify the default to be --no-as-needed.

Secondly, how is anyone supposed to "set their linker flags accordingly" if not in the catkin sources?
Do you propose I should patch my distributions _linker_ to satisfy requirements of ROS?
In my humble opinion, this is way too drastic a requirement.

I did not propose to make catkin aware of platform specific differences.
I proposed to add --as-needed to catkin's linking flags - this is what is expected of the linker by catkin,
so why not specify it explicitly when it's not the default on some (non-debian) systems?

v4hn

**Comment by dirk-thomas** [comment]
You can simply invoke CMake with arguments. There are three variables relevant for linker flags in CMake:
- CMAKE_EXE_LINKER_FLAGS http://www.cmake.org/cmake/help/v2.8.12/cmake.html#variable:CMAKE_EXE_LINKER_FLAGS
- CMAKE_MODULE_LINKER_FLAGS http://www.cmake.org/cmake/help/v2.8.12/cmake.html#variable:CMAKE_MODULE_LINKER_FLAGS
- CMAKE_SHARED_LINKER_FLAGS http://www.cmake.org/cmake/help/v2.8.12/cmake.html#variable:CMAKE_SHARED_LINKER_FLAGS

You can pass any of them to CMake (and catkin_make) via `-D<VARNAME>=<VALUE>`.

Since I don't have any platform at hand which has the problem you describe you might want to try the various options and check with which it works for you.

**Comment by dirk-thomas** [comment]
Currently `catkin` does neither specify `--as-needed` nor `--no-as-needed`. If a platform has a different default than others then I think it is reasonable to expect to work around it on that platform using the CMake variables mentioned above.

Therefore I am going to close this ticket since it is not planned to change anything in `catkin` atm.
