### ISSUE TITLE
CMAKE_EXPORT_COMPILE_COMMANDS=1

### ISSUE THREAD

**Issue by galou** [ros/catkin#698]
I guess adding the `set(CMAKE_EXPORT_COMPILE_COMMANDS ON)` (or something similar) in catkin's entry point, `CMakeLists.txt`, would not disturb anybody but it is useful for Vim's YouCompleteMe plugin.

On Ubuntu, the entry point for catkin is a symlink to `/opt/ros/indigo/share/catkin/cmake/toplevel.cmake`, thus is unmodifiable. Could this be added there by default?

Regards,
Gaël

**Comment by dirk-thomas** [comment]
Since this is kind of a special feature which might be only used by a few people I am not sure if catkin should always generate the compiler / linker commands (for everybody) by default. It might be easier if you pass the argument to the `cmake` / `catkin_make` invocation when performing the build.

Also the `toplevel.cmake` file only affects builds with a single CMake invocation. Isolated builds don't use it at all. I am not sure if the plugin you are using would work when the build space contains separate folders for each package, each having its own output file for compile commands?

**Comment by galou** [comment]
I thought it more as a suggestion than an issue and I didn't know that `toplevel.cmake` is not used with `catkin_make_isolated`.
The plugin I use (YouCompleteMe) is configured via a Python script, so I guess it wouldn't be a problem with separate folders.
I close the issue, thanks for answering.

**Comment by dirk-thomas** [comment]
Were you able to identify which parameters you had to pass to make it work for your use case?

**Comment by galou** [comment]
I use the plugin in combination with `catkin_make`, not `catkin_make_isolated`. For `catkin_make`, I run `catkin_make -DCMAKE_EXPORT_COMPILE_COMMANDS=1`.
According to http://wiki.yangleo.me/2013/10/27/YouCompleteMe-installation-and-configurations.html, to configure `YouCompleteMe`, you need to modify a line to the .ycm_extra_conf.py

```
compilation_database_folder = 'path/to/compile_commands.json'
```

Is that what you wanted to know?

**Comment by dirk-thomas** [comment]
Yes, then anybody who reads this in the feature can get it working with the same setup as you. Thanks!
