### ISSUE TITLE
support using gmock

### ISSUE THREAD

**Issue by dirk-thomas** [ros/catkin#699]

**Comment by v-lopez** [comment]
I am using this modification and it works properly.
But additional changes are needed in https://github.com/ros/ros_comm/blob/indigo-devel/tools/rostest/cmake/rostest-extras.cmake.em#L79 so the gtests added through add_rostest_gtest use the gtest version embedded within gmock, instead of the default one.

Otherwise I have code compiled against the "pure" gtest version, linking against the libgmock.so which provides gtest symbols but sometimes have different versions.

Using:    `include_directories(${GTEST_INCLUDE_DIRS})` in add_rostest_gtest is enough to make sure the gtest headers within gmock are found.
