### ISSUE TITLE
No warning when creating a package with a conflicted name.

### ISSUE THREAD

**Issue by BenBlumer** [ros/catkin#722]
I have a package I wrote to control gazebo. So I called it "gazebo_control". I added a service from it in Python  `from gazebo_control.srv import *`. Upon running this script, this produced the error `ImportError: No module named srv`.  Changing the name of the package fixed the error.  I'm not sure what this is about. If anyone else can confirm this happens to them, it's worth looking in to since it didn't even generate a warning about conflicting names. 

I'm running Indigo on Ubuntu 14.04.

**Comment by wjwwood** [comment]
Overlaying different versions of packages with the same name is an intended workflow. Usually, in that case, the two packages are the same package at different versions, but regardless `catkin` cannot easily know if you mean to overlay the package or if you accidentally created a package with same name.

The `catkin_create_pkg` command could certainly warn you if you're creating a package of the same name, but in general I don't think it is correct for `catkin` to complain if two packages with the same name exist in different workspaces.

Now, obviously `catkin` will complain if you put two packages with the same name in the same workspace, because in that case you cannot be overlaying them and that's an error.

It would be possible for `catkin` to just print a notice when building a package that it is overlaying an existing package, but we would want to be careful to make sure that any check is done efficiently.

**Comment by wjwwood** [comment]
This kind of sanity check or notice would also probably be better done in a tool like `catkin_make` or `catkin_make_isolated`/`catkin build`, since they have all the information in one place and the check can be done once instead once per package.

**Comment by BenBlumer** [comment]
Hmm. I could see the merit of that.

But I have no idea where this previous version of "gazebo_control" exists. I don't even know what it does/did. It's not in any workspace hat's currently sourced. So from the user perspective, I was spending a lot of time debugging my new package (combing through CMakeLists, double checking against tutorials, file paths, etc.) when really the problem was with some other package that exists god-knows-where. Without a notification or a way to be sure which package you're importing from, this could be a game-stopper for people.

**Comment by wjwwood** [comment]
I understand the confusion, and that's why I support the tools notifying you if you're overlaying incase you're not away of it.

**Comment by dirk-thomas** [comment]
@BenBlumer You can check the list of ROS packages in your current environment with `rospack list`.

**Comment by tfoote** [comment]
Unfortunately since there's no canonical list of packages we can't actually guarantee non-collision. In this case it collides with a released package, which could be checked. But there are many more unreleased packages.

I would suggest that your name choice is too generic if you're running into collisions like this. "control in the context of gazebo" is not well scoped, as can be seen if I ask, "Does xyz capability fall in that scope?" it's not clear what does and does not. 

There are a lot of packages out there and if you're following the [naming conventions](http://wiki.ros.org/ROS/Patterns/Conventions#Naming_ROS_Resources) in general these things should not collide. And there's a level whenever you pick a name that you should verify that it's not already used. 

I agree that providing some more visibility into what's being overlayed would be valuable. Though there's a risk of being overly verbose once you get to large workspaces with large overlays.

**Comment by BenBlumer** [comment]
Dirk, gazebo_control actually doesn't show up in my rospack list now that I've changed the name of the package I created. I'm not sure what that's about!

Tfoote, the name could be more specific for sure. Though, for my application, it's scoped by the fact that it's in a workspace dedicated to my thesis. In the context of my thesis workspace, it is very clear what gazebo_control does, and the package is totally useless without the other packages in the workspace (launch files to set up the world it controls, the SDF models it's driving, etc.).

**Comment by dirk-thomas** [comment]
Have you tried to figure out where the Python package is located:

```
python -c "import gazebo_control; print(gazebo_control.__file__)"
```

And then checked from which Debian package it comes from:

```
dpkg -S /path/to/file
```

**Comment by dirk-thomas** [comment]
As @tfoote mentioned before printing all overlayed packages for your use case would be overly verbose and therefore I don't think `catkin_make(_isolated)` should do that. Since there are already numerous way to find existing packages (as mentioned above) I will close this ticket and mark it with the label "wontfix".
