### ISSUE TITLE
cmi --install develspace setup.bash has surprising C_P_P

### ISSUE THREAD

**Issue by tkruse** [ros/catkin#749]
To reproduce, follow Jade installation instructions, then:

```
./src/catkin/bin/catkin_make_isolated --install -DCMAKE_BUILD_TYPE=Release
. devel_isolated/setup.bash 
echo $CMAKE_PREFIX_PATH 
.../jade_comm_underlay/devel_isolated/test_rostopic:.../jade_comm_underlay/install_isolated
```

Not sure if that is a feature or a bug.

**Comment by dirk-thomas** [comment]
A package has currently only one parent `CMAKE_PREFIX_PATH`. For a package `foo` that means it can either depend on the devel space of package `bar` or on the install space of package `bar`.

When you don't use `-install` all packages depend on the devel spaces of their dependencies. But when you use `--install` each package depends on the install space of their dependencies. Therefore you see the non-intuitive result you described when you use `--install` and then source an isolated package from the devel space since it depends on the install spaces of the other packages.

I would think that `catkin_tools` will have the same non-intuitive behavior. @jbohren @wjwwood May be you can comment if that is the case?

A simple work around to the problem is to invoke `catkin_make_isolated` without `--install` to make the devel spaces chain as you want them to.

It might be possible to extend `catkin_make_isolated` in a way to make isolated devel spaces only depend on the devel spaces of their dependencies (if they are within the same workspace). I assume it would require passing `CMAKE_PREFIX_PATH` into the CMake invocation. Since that is an easy way to work around the problem you described and I assume a "fix" would require handling two `CMAKE_PREFIX_PATH`s within catkin's CMake code I don't plan to work on this in the future (and therefore marked the ticket with the milestone `untargeted`).

**Comment by tkruse** [comment]
Thanks for the explanation. However, in the example I did not source a single package (I believe), I sourced the whole devel space, so the test_rostopic entry in the C_C_PC is extra confusing.

In general I find it confusing that the develspace changes depending on whether I use --install or not. Not sure if this has always been the case, and I just never noticed.

**Comment by dirk-thomas** [comment]
The setup file in the devel / install space only redirects to the last package in the topological order when built in isolation. So it is identical to source the root of all devel / install spaces and to source the last package devel / install space.

Since `test_rostopic` is a package in the workspace it will appear in the environment variables. The decision to not create a Debian package for this package happens at release time - in the source repository it is a package like any oither.

I understand that it is not intuitive but I have described the technical reason why that is the case. I am pretty sure that this has been the behavior all the time since implementing the behavior you expect instead is pretty complex and has never been implemented.

**Comment by tkruse** [comment]
In that case I suggest closing this issue, since it is not a bug, and not interesting enough to track.
