### ISSUE TITLE
Add use of catkin_EXPORTED_TARGETS to catkin_create_pkg's created CMakeLists.txt

### ISSUE THREAD

**Issue by bit-pirate** [ros/catkin#754]
I believe many (most?) users/devs are not yet aware of the new way to add dependency on messages. That is in the package's CMakeLists.txt:

```
add_dependencies(your_program ${catkin_EXPORTED_TARGETS})
```

Instead of the old and current

```
add_dependencies(your_program some_messages_generate_messages_cpp)
```

See catkin documentation: http://docs.ros.org/api/catkin/html/howto/format2/cpp_msg_dependencies.html

and ROS Answers: http://answers.ros.org/question/52744/how-to-specify-dependencies-with-foo_msgs-catkin-packages/?answer=75340#post-id-75340

To make this new way better known, I suggest to add this as the default for the CMakeLists.txt created by `catkin_create_pkg`.

Also, the CMakeLists.txt reference should be updated: http://wiki.ros.org/catkin/CMakeLists.txt#Important_Prerequisites.2BAC8-Constraints (I can do that, after a catkin maintainer confirms).

**Comment by dirk-thomas** [comment]
`catkin_create_pkg` is provided by the Python package `catkin_pkg` rather then by `catkin` itself. I also think the change you propose has already been implemented and released a few month ago: ros-infrastructure/catkin_pkg#79

There are information in so many different location that it is almost impossible to update them consistently. Please go ahead an update the wiki page.

**Comment by bit-pirate** [comment]
> catkin_create_pkg is provided by the Python package catkin_pkg rather then by catkin itself.

My bad. Sorry.

> I also think the change you propose has already been implemented and released a few month ago: ros-infrastructure/catkin_pkg#79

Right. This should fix it.

Since I'm running Ubuntu Trusty I only have version 2.8.1., but the fix got into 2.9. Will that version be released for Trusty?

> Please go ahead an update the wiki page.

Done.

**Comment by dirk-thomas** [comment]
Since `python-catkin-pkg` is a distro agnostic release it should be available for all ROS and Ubuntu distros. Currently it seems to be only in shadow-fixed (http://packages.ros.org/ros-shadow-fixed/ubuntu/pool/main/p/python-catkin-pkg/) but not in the main repo (http://packages.ros.org/ros/ubuntu/pool/main/p/python-catkin-pkg/) yet. For a Python release that should never be the case since releases are pushed directly to all repos.

@tfoote Can you please look into why the two last releases of this package are not available in the main repo and fix it.

**Comment by tfoote** [comment]
catkin-pkg 0.2.10 is now in the public repo.

**Comment by bit-pirate** [comment]
> catkin-pkg 0.2.10 is now in the public repo.

Got it. Thanks!
