### ISSUE TITLE
Byte-compiling python failure should fail the install target

### ISSUE THREAD

**Issue by mikepurvis** [ros/catkin#788]
If you `catkin_make install` a Python package containing syntax errors, there is a byte-compiling error message thrown, but Make still returns 0 as if it was successful. This feels like a wrong behaviour to me.

**Comment by wjwwood** [comment]
Is the same true if you have a normal `setup.py` file (no catkin or CMake)?

**Comment by mikepurvis** [comment]
This guy reports having setup.py issues: http://stackoverflow.com/questions/25942370

But my own test shows that it does pretty much what catkin does— coughs up the error message without actually failing anything. Doesn't look like there's a flag or anything to make that any more strict, so perhaps there isn't much catkin could/should do here.

**Comment by wjwwood** [comment]
There might be a separate verb you can pass to `setup.py` which when byte-compiling fails it returns a non-zero exit code. I recently had the problem that you couldn't install the osrf_pycommon deb for Python2, because the post install hook would try to byte-compile Python3-only files which would fail and the deb would not install.

**Comment by dirk-thomas** [comment]
I will close this for now since we don't know how this could be handled differently. If you find a way to achieve this please comment here / open a pull request to add this check.
