### ISSUE TITLE
Allow indirect buildtool-depend on `catkin`

### ISSUE THREAD

**Issue by NikolausDemmel** [ros/catkin#789]
The [code in `catkin_package`](https://github.com/ros/catkin/blob/5f653c01e531f4360942d737e0f8e3fc37d93c46/cmake/catkin_package.cmake#L107-L116) checks if `catkin` is a direct buildtool-depend of the current package.

IMO, it should be also ok if catkin was a indirect buildtool depend, meaning that it is a buildtool-export-depend of at least one of the current packages' buildtool-depends.

One use case is `catkin_simple`. Currently, when using `catkin_simple`, you have to always specify both `catkin` and `catkin_simple` as buildtool-depends. With this change, it would suffice to specify buildtool-depend on `catkin_simple`.

I'm not sure how to check for that. How can we access dependency information for other packages?

**Comment by dirk-thomas** [comment]
Currently transitive dependencies are not available within CMake. Therefore I don't see a good way of checking them.

One option would be for `catkin_simple` to _manipulate_ `${PROJECT_NAME}_BUILDTOOL_DEPENDS` to insert `catkin` if `catkin_simple` is in there but not `catkin`. Not very nice but would work for the described case.

**Comment by NikolausDemmel** [comment]
> Currently transitive dependencies are not available within CMake. Therefore I don't see a good way of checking them.

Would catkin with its current dependencies (catkin-pkg, ...) have the capabilities to implement this, or would we need to pull in additional dependencies (without reimplementing functionality)? If the latter, I would just go for the workaround.

> One option would be for catkin_simple to manipulate ${PROJECT_NAME}_BUILDTOOL_DEPENDS to insert catkin if catkin_simple is in there but not catkin. Not very nice but would work for the described case.

Good idea. Despite maybe not being conceptually nice, it should work well enough. Thanks.

**Comment by dirk-thomas** [comment]
On-demand parsing is not an option due to the necessary overhead. Each package CMake config file would need to embed its dependencies when it is built. All the pieces are in place since each package already extracts the dependencies when it is being built.

But exposing the dependencies  in the CMake config also makes each package a little bit more "diffferent" then normal CMake packages.

**Comment by NikolausDemmel** [comment]
> But exposing the dependencies in the CMake config also makes each package a little bit more "diffferent" then normal CMake packages.

Is that an anti-goal? For one it is already the case and moreover those additions would not change the semantics of the standard interfaces like `_LIBRARIES` etc. I thought it was quite normal that some find-modules in CMake (not just catkin packages) set some package specific variables on top of the standard variables.

In any case the workaround for catkin_simple you described might still be more reasonable for now.

**Comment by dirk-thomas** [comment]
I will close this since the originally mentioned issue should be fixed / worked around by `catkin_simple`. Please feel free to also create a pull request which embeds all dependencies into the generated CMake config file. While I might not like the idea it doesn't do any harm and if it supports any use case that is fine by me.
