### ISSUE TITLE
Please remove the build space or pick a different build space?

### ISSUE THREAD

**Issue by libing64** [ros/catkin#794]
I upgrade the ros-indigo-catkin today, then I cannot compile the package now, maybe this is a bug?
"The build space at '/home/xxx/catkin_ws/build' was previously built by 'catkin build'. Please remove the build space or pick a different build space."

I am always using catkin_make. 

Additionally, anyone knows how to roll the catkin_make version back to the last version?

**Comment by dirk-thomas** [comment]
Please post the content of the following file: `/home/xxx/catkin_ws/build/.built_by`

**Comment by wjwwood** [comment]
@libing64 it might be a bug, which is why @dirk-thomas asked for the content of the `.built_by` file, but likely it was that you at one point built the workspace with `catkin build` and then later tried to use `catkin_make`. These are not compatible enough to use the same build folder without issues, so this is why you get this warning.

Please post the file and any commands you can remember using so we can determine it is not a bug, but after that you can likely work around the issue by deleting the `build` folder (as well as the `devel` and `install` folders for good measure) and running `catkin_make` again.

**Comment by libing64** [comment]
@dirk-thomas The content of .built_by is
   catkin build
Great thanks.
@wjwwood Maybe I once tried some ros package which is not under ros-indigo, so the catkin build was used. 
Since there is a lot of packages under the catkin_ws, I don't want to delete the build and devel directory and recompile all the packages. 
After settinf the content of .build_by to "catkin_make", catkin_make works well now. Thanks.
