### ISSUE TITLE
Warning to display when user adds executable named "test"

### ISSUE THREAD

**Issue by bmagyar** [ros/catkin#797]
Hi guys,

A friend bumped into this issue today that was also unknown to me.
Turns out that
`add_executable(test src/test.cpp)`
leads to exactly _nothing_. No warning, no executable. Only a slightly confused user looking for their executable.

Sorry that I'm doing this in a rush now, I was only able to find this reference to the issue.
https://cmake.org/Bug/bug_relationship_graph.php?bug_id=12960&graph=relation

Of course - one could say - CMake reserves the target named "test" for the tests to be generated in the Makefile. `make test` is standard.

I'd propose a solution but I'm not proficient enough with the internals of catkin. I think displaying a warning for this would save some gray hair for people, if anyone could add this that would be much appreciated.

Cheers,
Bence

**Comment by wjwwood** [comment]
Both the `test` target being reserved and the `add_executable` macro are part of CMake. I don't think it's `catkin`'s responsibility to warn about this and in order to do so we'd have to perfectly override the `add_executable` macro. This is tricky since you cannot override it more than once, see: https://cmake.org/pipermail/cmake/2011-March/043320.html So if we were to override it, and someone else was already overriding it, then it would potentially result in an infinite loop.

Unfortunately, I think the best thing to do is to push on the upstream ticket to which you linked.

**Comment by dirk-thomas** [comment]
This is already being addressed by newer CMake versions and the policy [CMP0037](https://cmake.org/cmake/help/v3.0/policy/CMP0037.html).

**Comment by bmagyar** [comment]
Ok, thanks for the explanation guys!
