### ISSUE TITLE
Is it possible to add an arbitrary binary using gmock as test?

### ISSUE THREAD

**Issue by SirVer** [ros/catkin#830]
I have a test binary that depends on many `add_library` calls in my `CMakeLists.txt`. It also requires a ton of flags for which I added a couple of useful macros for my particular use case. It also require a full gmock built from source and do not want `catkin_add_gtest` to link some other version into my binary. So I cannot use `catkin_add_gtest`.

What I do require is the [path magic done here](https://github.com/ros/catkin/blob/kinetic-devel/cmake/test/gtest.cmake#L36)  so that run_tests finds the binary.

Is there a way to only get that? Something like `catkin_add_target_as_test`?

**Comment by dirk-thomas** [comment]
You should be able to call `catkin_run_tests_target` with your executable. Instead of trying to get the location of the binary you should use a generator expression instead. That way CMake can expand the location for different build configurations on platforms like Windows.

## 

Please ask future questions like this on [answers.ros.org](http://answers.ros.org/). The rational for asking all kind of questions in a single place is:
- There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
- In the future other users will search there for similar problems and can find your question and the potential answers.
- The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

**Comment by SirVer** [comment]
Thanks for the answer. This is in fact exactly what I did ([see here](https://github.com/googlecartographer/cartographer/blob/master/cmake/functions.cmake#L238)), but I still run into issues - catkin seems to be building a gtest of its own (which Cartographer does too) - even if I never call `add_gtest`. This causes conflicts (see linked issue). Please advise how I can use `catkin_run_tests_target` without catkin searching for gtest.

Edit: I do not think this is a `question` - there is a bug lurking here in the semantics/ergonomics, we just need to find out what exactly it is.

**Comment by dirk-thomas** [comment]
Support for `gmock` within `catkin` is a long standing feature request: see #699. Until that is available you need to take care of setting up and compiling `gmock` (including the matching `gtest` version) yourself. If you take care of that before calling `find_package(catkin ...)` `catkin` will later just use your version of gtest instead of insisting to create its own targets (see https://github.com/ros/catkin/blob/1c2ad7cd1ab17c1890ace371c08217163a59c3a1/cmake/test/gtest.cmake#L153-L162).

**Comment by dirk-thomas** [comment]
@SirVer Have you tried using `gmock` before finding `catkin` and does it workaround the problem?

**Comment by SirVer** [comment]
@damonkohler Damon looked into this issue on our end. I am unsure what he ended up doing exactly.

**Comment by damonkohler** [comment]
Here's our (probably fragile) approach to this:

1. [find_package(GMock)](https://github.com/googlecartographer/cartographer_ros/blob/master/cartographer_ros/CMakeLists.txt#L40)
2. [find_package(catkin)](https://github.com/googlecartographer/cartographer_ros/blob/master/cartographer_ros/CMakeLists.txt#L42)
3. [Override the GTEST_XXX variables](https://github.com/googlecartographer/cartographer_ros/blob/master/cartographer_ros/CMakeLists.txt#L63)

This works because find_package(catkin) calls find_package(GTest), fails to find it, [then aborts](https://github.com/ros/catkin/blob/1c2ad7cd1ab17c1890ace371c08217163a59c3a1/cmake/test/gtest.cmake#L94) doing any more work because find_package(GMock) creates a target called 'gtest'.

**Comment by dirk-thomas** [comment]
While certainly not being pretty it sounds like it works for your use case. Until #699 gets addressed I think it is the best way for now.

Therefore I will close this ticket. Please feel free to comment and the ticket can be reopened.
