### ISSUE TITLE
Problem with sourcing setup.bash

### ISSUE THREAD

**Issue by Eirtrand** [ros/catkin#865]
Hi, I have some packages installed with apt, and some from from source in catkin_ws. The problem Im having is that the source `/opt/ros/kinetic/setup.bash` file and the `~/catkin_ws/devel/setup.bash` file conflicts. As soon as I source catkin I can not find some packages In opt/ros, and as soon as I source opt/ros I can not find any of my catkin nodes. I have been struggling with this for a while now and Im wondering if it is a way of resolving this conflict?

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.
