### ISSUE TITLE
Adjust PyPi category to allow only Python 2?

### ISSUE THREAD

**Issue by bmagyar** [ros/catkin#877]
Hiya,

Today I ran into the unpleasant problem posed by having multiple pip-s on my system. 
I was getting string parsing problems from `catkin_generate_changelog` due to it running on Python3. 
Cleaning `catkin-pkg` from my Python3 packages solved the issue. 

I had a look at how PyPi indices are set for `catkin-pkg` [here](https://pypi.python.org/pypi/catkin_pkg/0.3.5) but didn't go very deep into this repo to see where this info gets injected into the `setup.py` file. 

To save some headache for people the category could be changed to `
Programming Language :: Python :: 2 :: Only` so PyPi wouldn't let `pip3` install `catkin-pkg`.
The full list of classifiers PyPi filters for can be found [here](https://pypi.python.org/pypi?%3Aaction=list_classifiers)

**Comment by dirk-thomas** [comment]
First the repo containing `catkin_pkg` is https://github.com/ros-infrastructure/catkin_pkg/ and not this repo.

The Python package is designed to work with both Python 2 as well as 3. We ship Debian packages of that package with the `python-` as well as the `python3-` prefix. So the setup file shouldn't limit the Python version of the package.

You might want to look into other causes why it fails in your case. Please include more information into your report since otherwise it is difficult to give any advice / feedback. You might have your `PYTHONPATH` set to point to packages from a different Python version but that is just pure speculation.

**Comment by dirk-thomas** [comment]
I will close this ticket for now due to no response. Please feel free to comment and the ticket can be reopened is necessary.
