### ISSUE TITLE
Assertion failed: check for file existence

### ISSUE THREAD

**Issue by CT-Yang** [ros/catkin#881]
When I type command  `$catkin build ` , I get cmake error like follow:

![image](https://user-images.githubusercontent.com/28501254/28755282-b87a445a-7589-11e7-855f-c38661768c64.png)

Before, if the code in src file don't include the image_transport related libraries, I can run  `$catkin build ` without any error.

Wonder that what will cause this problem because I can't find any solution in the internet.Tks for help!

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.

**Comment by CT-Yang** [comment]
Tks for ur reply :)
