### ISSUE TITLE
"catkin_make_isolated --install "with --pkg other than 1st fails if install dir is empty / nonexistent

### ISSUE THREAD

**Issue by kjaget** [ros/catkin#890]
For anything other than the first package in the list, CMI tries to build using "<install_dir>/env.sh cmake ..." but env.sh isn't there.  Looks like the code updates to use env.sh after the first package is skipped. But if this is the first time running cmi after cleaning out the install directory nothing would have been installed so the directory will be non-existent or empty.  Thus "env.sh cmake ..." fails because env.sh can't be found.

**Comment by dirk-thomas** [comment]
The [documentation](https://github.com/ros/catkin/blob/1bb11b704385f6ea7a8a055a6ee3df1c67b3df10/bin/catkin_make_isolated#L56-L58) of the command line option `--pkg` says:

> Process only specific packages (only after catkin_make_isolated has been invoked before with the same install flag)

If you clean the install directory you must install the dependency packages again in order to be able to build a specific package.

**Comment by kjaget** [comment]
Ah, ok, thanks.

**Comment by dirk-thomas** [comment]
Please close the ticket if the question is resolved.
