### ISSUE TITLE
Allowing relative include directories other than "include" in the install space cmake config file

### ISSUE THREAD

**Issue by kartikmohta** [ros/catkin#895]
Currently, when generating the `<package>Config.cmake` for install space, catkin only allows the `include` directory to be present as a relative path. Is there a reason (other than convention) for not respecting any other relative paths specified in the `INCLUDE_DIRS` option of the `catkin_package` function?
For example, if I try to export the `include/<package>` folder using the `INCLUDE_DIRS` option, the generated cmake config file in the install space only contains `include` in the list. Note that the devel space cmake config file seems correct, though it contains the full absolute path of the folder specified in the `INCLUDE_DIRS` option.

**Comment by dirk-thomas** [comment]
In the devel space multiple locations are common that is why all passed paths are preserved. In the install space the expectation is that almost all package install their headers into `include`. The API makes this easy for the common case.

You are not limited though to this single catkin API. You can always export an extra file using `CFG_EXTRAS` in which you can do arbitrary stuff. E.g. append a custom value to `<pkgname>_INCLUDE_DIRECTORIES`.

Changing the current semantic of the exported `INCLUDE_DIRS` would be difficult since it would change the behavior of existing packages which pass more than `include` to that argument. Therefore I recommend you use an extra file to set non-standard include directories.

**Comment by kartikmohta** [comment]
Thanks for the detailed answer! 🙂
