### ISSUE TITLE
REALLY annoying to work with messages

### ISSUE THREAD

**Issue by dbersan** [ros/catkin#900]
Well, I've seen some people having this problem before, so I'll just point out the issue. 

Yes I know, there are documentation pages out there explaining how to set up the CMakeLists.txt to reinforce message dependency or message headers dependencies from one package to another, or messages from the same package, etc. I know in case I get some _**fatal error:** message_package/msg.h: No such file or directory #include "message_package/msg.h"_ I might just go read them all again and spend an hour trying the different combinations of solutions until it compiles. 

But please, could you make this a little simpler? It's almost as annoying as mandatory windows upgrades. Just build the goddamn msg headers first or something.

**Comment by sloretz** [comment]
Thanks for the feedback. It sounds like you've seen the documentation, but want to write less CMake code to generate and depend on messages. I'm not sure which part of the process you would like simplified. Please consider submitting a pull request with the changes you would like to see.

For anyone coming across this looking for documentation: 

* http://wiki.ros.org/catkin/CMakeLists.txt
* http://docs.ros.org/kinetic/api/catkin/html/howto/format2/cpp_msg_dependencies.html
* https://cmake.org/cmake/help/v3.0/command/include_directories.html
* https://cmake.org/cmake/help/v3.0/command/add_dependencies.html

**Comment by NikolausDemmel** [comment]
I agree that it would be great if you could suggest a concrete way to improve the workflow that would help you avoid this problem. Otherwise it is a bit like complaining "please make C++ simpler, I'm always getting memory leaks and every time it takes me forever to fix it".

One way to ensure you don't have to worry about this is:

1. Use catkin_tools instead of catkin_make
2. Only define messages in pure message packages (i.e. packages which only have messages and no code).
3. Possibly even use [catkin_simple](https://github.com/catkin/catkin_simple) for writing even less cmake code

In my analogy this is maybe like suggesting "use python instead, if you don't want to worry about memory management".

**Comment by NikolausDemmel** [comment]
Also, there is [catkin_lint](https://github.com/fkie/catkin_lint) that does static analysis on your cmake files to check for common errors. Not sure if in your case it would detected the issue, but you could give it a try.

**Comment by dirk-thomas** [comment]
The current documentation on this topic is pretty detailed. Also the example code generated for new packages contains a lot of helpful information in the CMake file. Therefore I will close this ticket for now since there is simply not enough information to act on. Please feel free to propose specific improvements here and the issue can be reopened. Even better would be to contribute them directly with a pull request.

> Use catkin_tools instead of catkin_make

An isolated build (which can also be done with `catkin_make_isolated` only addresses the problem for cross-package target dependencies. Within a single package an explicit declaration of the target dependencies is still necessary.

**Comment by NikolausDemmel** [comment]
> An isolated build (which can also be done with catkin_make_isolated only addresses the problem for cross-package target dependencies. Within a single package an explicit declaration of the target dependencies is still necessary.

This doesn't arise if you also follow my suggestion 2. Or am I mistaken?

**Comment by dirk-thomas** [comment]
> Only define messages in pure message packages (i.e. packages which only have messages and no code).

Yes, this avoids the problem of target dependencies within one package. When using `catkin_make` it still has the cross-package dependency problem though.
