### ISSUE TITLE
New release request

### ISSUE THREAD

**Issue by bmagyar** [ros/catkin#910]
Could we please have a new release of `catkin`? We'd really like to use GMock without having to locally duplicate the repo.

**Comment by dirk-thomas** [comment]
A new catkin release is rather "expensive" since it require to rebuild almost every package across all platforms. Therefore we do releases of such core packages only rarely. With the preparations for ROS Melodic the next release will likely happen within the next 3-4 weeks.

**Comment by bmagyar** [comment]
Thanks for the heads up!

**Comment by dirk-thomas** [comment]
The upstream release of version 0.7.9 is done. The release PRs are still pending since they will wait for several other ROS core packages to be released:
* ros/rosdistro#16805
* ros/rosdistro#16806

I will close this ticket now. Please feel free to subscribe to the pending PRs on the `rosdistro` repo to get notified when the release is being processed by the buildfarm. It might be a while though.

**Comment by bmagyar** [comment]
Thanks a lot!

**Comment by dirk-thomas** [comment]
@bmagyar @v-lopez The `gmock` related changes make the build of the melodic package of `catkin` fail: http://build.ros.org/view/Mdev/job/Mdev__catkin__ubuntu_bionic_amd64/

Either we will be able to fix this rather soon or I will have to revert the changes for now.

**Comment by v-lopez** [comment]
I'll look into it today.

**Comment by scott-eddy** [comment]
@v-lopez @dirk-thomas is there any updates on the GMock update?  I would love to be able to include GMock properly with catkin using a distro release of catkin

**Comment by dirk-thomas** [comment]
This has been addressed long ago. The latest release 0.7.12 if from the beginning of February.
