### ISSUE TITLE
find_package auto load CFG_EXTRAS cmake files

### ISSUE THREAD

**Issue by Wsine** [ros/catkin#911]
project struct

```
~/catkin_ws/src
├── packageB
│   ├── CMakeLists.txt
├── packageA
│   ├── cmake
│   │   ├── cmakeA.cmake
│   │   └── cmakeB.cmake
│   ├── CMakeLists.txt
```

```
### packageA/CMakeLists.txt
file(GLOB_RECURSE all_cmake_files
    RELATIVE "${CMAKE_CURRENT_SOURCE_DIR}/cmake"
    "${CMAKE_CURRENT_SOURCE_DIR}/cmake/*.cmake")
catkin_package(
    INCLUDE_DIRS include
    LIBRARIES ${PROJECT_NAME}
    CFG_EXTRAS ${all_cmake_files})
```

```
### packageB/CMakeLists.txt
find_package(catkin REQUIRED COMPONENTS packageA)
```

however, **cmakeA.cmake includes cmakeB.cmake file**, and catkin_make will auto load cmakeA.cmake.

the error message is here:

```
CMake Error at packageA/cmake/cmakeA.cmake:10 (include):
  include could not find load file:

    cmakeB
Call Stack (most recent call first):
  /home/wsine/catkin_ws/devel/share/packageA/cmake/packageAConfig.cmake:190 (include)
  /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:76 (find_package)
  packageB/CMakeLists.txt:6 (find_package)
```

absolutely, **packageA/cmake isn't in CMAKE_MODULE_PATH**. please help,

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.
