### ISSUE TITLE
CMake config file for message packages and bindings for new languages

### ISSUE THREAD

**Issue by drdanz** [ros/catkin#920]
In order to generate bindings for other languages not officially supported by ROS, it is useful to have packages containing only the message files (for example the [`ros-std-msgs`](https://tracker.debian.org/pkg/ros-std-msgs) in debian "official" packaging). These packages do not require to install any other dependency, since they only contain the message definition files.

It would be nice if from a standard CMake project (i.e. not using catkin) you could do something like this:

```cmake
find_package(std_msgs COMPONENTS messages)
add_binding_for_some_language("${std_msgs_DATAROOTDIR}/std_msgs/msg/String.msg")
```

Unfortunately the generated `std_msgsConfig.cmake` file has at least the dependency on `message_runtime`, and therefore it cannot be installed with the debian `ros-std-msgs` package.

Concluding:
* Config files generated by catkin for message packages should have a "COMPONENT" for message files
* They should have some variable (in this example `std_msgs_DATAROOTDIR`) pointing to the directory where the message files were installed
* It should be possible to include these config files when only the message files are installed.

**Comment by dirk-thomas** [comment]
> Unfortunately the generated `std_msgsConfig.cmake` file has at least the dependency on `message_runtime`, and therefore it cannot be installed with the debian `ros-std-msgs` package.

As you noticed yourself message packages *do* have dependencies, e.g. on `message_runtime`. This dependency is mandatory since e.g. some of the generated headers for messages will require transitive headers provided by `message_runtime`.

I don't see why the Debian package cannot be installed though. You should be able to install it perfectly fine together with its dependencies. Why would you need to avoid the installation of `message_runtime`?

> Config files generated by catkin for message packages should have a "COMPONENT" for message files

Even if the CMake config file would support `COMPONENTS messages` that would still not get rid of the dependency on `message_runtime` in the Debian package. So I don't see how that would help your case.

> They should have some variable (in this example `std_msgs_DATAROOTDIR`) pointing to the directory where the message files were installed

Message definitions are already being installed in a known location under `<install-prefix>/share/<pkgname>/msg` so you can already get the location by using `${std_msgs_DIR}/../msg` (the CMake variable point to the directory which contains the CMake config file of the package: `<install-prefix>/share/<pkgname>/cmake`).

---

Maybe you can describe your general goal before to provide more context on what you want to achieve.

**Comment by drdanz** [comment]
> Maybe you can describe your general goal before to provide more context on what you want to achieve.

Thank you for the prompt reply, I'll try to explain what I'm trying to do:

In [YARP](https://github.com/robotology/yarp/), we have a compatibility layer with ROS, and a tool that generates the code to use ROS types with YARP, from the `.msg` files. This layer does not depend on any ROS package (we have a re-implementation of the protocols "spoken" by ROS), nor on catkin.

At the moment we ship the `.msg` files with the code, but what I would like to do is to find these files installed on the system instead. Eventually I'm planning on making "message libraries" like the ones you provide for ROS, but for YARP. I already made some successful tests using the `find_path()` CMake command in order to locate the `.msg` files, and that's probably enough for my goal, but I was wondering if there is a way to improve the catkin generated packages, so that I don't have to make random guesses on the location of the message files.


> As you noticed yourself message packages do have dependencies, e.g. on `message_runtime`. This dependency is mandatory since e.g. some of the generated headers for messages will require transitive headers provided by `message_runtime`.

These dependencies are mandatory for headers/libraries generated from the message files, but there is no reason to have them if you don't use the headers, but just the `.msg` files, in order to generate bindings for some other language or framework, like in my case.


> I don't see why the Debian package cannot be installed though. You should be able to install it perfectly fine together with its dependencies. Why would you need to avoid the installation of `message_runtime`?

If I install the `libstd-msgs-dev` package on debian, I get the following packages that are useless in my use case:

```
libconsole-bridge-dev libconsole-bridge0.2v5 libcpp-common0d libroscpp-core-dev libroscpp-serialization0d librostime0d ros-message-runtime
```

All I need are the CMake files that at the moment are in the `libstd-msgs-dev` package... On the other hand, even if the CMake files were in the `ros-std-msgs` (that does not have any dependency), `find_package(std_msgs)` would just fail due to the missing dependency.


> Even if the CMake config file would support `COMPONENTS messages` that would still not get rid of the dependency on `message_runtime` in the Debian package. So I don't see how that would help your case.

The check on `message_runtime` could be performed for all the `COMPONENTS` except for the `message` one.


> Message definitions are already being installed in a known location under `<install-prefix>/share/<pkgname>/msg` so you can already get the location by using `${std_msgs_DIR}/../msg` (the CMake variable point to the directory which contains the CMake config file of the package: `<install-prefix>/share/<pkgname>/cmake`).

The problem is that I don't have the `std_msgs_DIR` variable, that's what I'm trying to determine with the `find_package(std_msgs)`, I cannot use `catkin`, nor workspaces, and therefore I have to guess the paths. On debian the install prefix for the package is `/usr`, but if the package is installed somewhere else (e.g. in a catkin workspace) it is not so easy to guess the path. The `CMAKE_PREFIX_PATH` variable should be enough if the config file supported this...


I hope this clarifies!

**Comment by dirk-thomas** [comment]
> These dependencies are mandatory for headers/libraries generated from the message files, but there is no reason to have them if you don't use the headers, but just the `.msg` files, in order to generate bindings for some other language or framework, like in my case.

This basically boils down to Debian package granularity. Currently every ROS package results in exactly one Debian package. I understand that for your use case a package only containing the message definitions but with the same argument it would also be justifiable that the generate code for each language could be split into separate Debian packages (why should I install a package which contains C++ if all I want to use is Python). At some point there needs to be a line when to stop splitting those up and the ROS package is currently that boundary.

Since it is very unlikely that we will change the packaging process for this use case it is probably fine to `find_package(std_msgs)` and the support for `COMPONENTS message` wouldn't be beneficial. If you would like to provide PRs to implement support for this that would be great. But it would still not address the packaging problem (splitting it up into multiple packages).

If you use the packages as they are you don't have to guess anything in the process but can construct the path from available variables:

* the base: `${<pkgname>_DIR}/..`
* the list of message files: `${<pkgname>_MESSAGE_FILES}` (see https://github.com/ros/genmsg/blob/0bfdc5acf26fc2ab5cf085acf53d3f417706d38e/cmake/pkg-msg-extras.cmake.in)
* even the dependencies on other message package is available if necessary: https://github.com/ros/genmsg/blob/0bfdc5acf26fc2ab5cf085acf53d3f417706d38e/cmake/pkg-msg-paths.cmake.installspace.in

---

A different approach from looking in the existing system for message packages would be to implement a custom message generator package (like `gencpp` and `genpy`). That would then require to build the message package again with that generator being present but would not require any of this and also allow you to have the generated code of your generator as a part of the Debian packages for each message package. E.g. `gennodejs` has been added some time ago. But I guess that would not be a process which fits your use case.

**Comment by dirk-thomas** [comment]
I will close this ticket for now since I don't think there is anything to do in this package. Please feel free to continue commenting in it.
