### ISSUE TITLE
#897 breaks workspace with cartorgrapher_ros

### ISSUE THREAD

**Issue by cwecht** [ros/catkin#926]
I have a workspace on a ubuntu 16.04 64-bit machine consisting of:
  
- [ceres-solver](https://ceres-solver.googlesource.com/ceres-solver.git)(1.13.0)
- [cartographer](https://github.com/googlecartographer/cartographer.git)(0.3.0)
- [cartographer_ros](https://github.com/googlecartographer/cartographer_ros.git)(0.3.0)

I need to build this workspace using `catkin build` because it contains non-catkin-packages.
If I try to build this with a recent version of catkin (0.7.11), I get this error

> CMake Error at /opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake:381 (add_library):
  add_library cannot create imported target "gmock" because another target
  with the same name already exists.
Call Stack (most recent call first):
  /opt/ros/kinetic/share/catkin/cmake/all.cmake:147 (include)
  /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:20 (include)
  CMakeLists.txt:44 (find_package)

This is caused by the changes in #897. ceres already defines the targets `gmoc` an `gmoc_main`.

**Comment by dirk-thomas** [comment]
Please include the information about your platform / environment e.g. what exact version you are having installed.

**Comment by cwecht** [comment]
Added version information in the first post.

**Comment by dirk-thomas** [comment]
It seems that neither of the packages is released / registered with ROS atm. That is why we didn't catch this problem.

I don't know much about these packages but `ceres` seems to not use `catkin` directly so I should not be affected.

`cartographer` and `cartographer_ros` seems to use custom CMake function to find `GMock` before `catkin`. Maybe it would be sufficient to update those by changing the order of these two steps - or even remove the `GMock` lookup completely since `catkin` includes that functionality now.

**Comment by cwecht** [comment]
Never mind, there is a fix for `cartographer_ros` for this...

**Comment by dirk-thomas** [comment]
For reference: googlecartographer/cartographer_ros#768
