### ISSUE TITLE
${prefix}/lib/cmake/<package>/<package>Config.cmake not detected

### ISSUE THREAD

**Issue by v4hn** [ros/catkin#938]
OMPL moved their cmake configuration files to `${prefix}/lib/cmake/ompl/omplConfig.cmake` in their first melodic release, but catkin does not find them there. This is a blocker for a MoveIt release to melodic at the moment ([see here](https://github.com/ros-planning/moveit/issues/806#issuecomment-390055091)).
@mamoll said he is willing to change it again, but the problem will likely pop up again for another library at some point.

https://cmake.org/cmake/help/v3.11/command/find_package.html lists a number of locations where cmake configurations are looked up by default. Citing

```
<prefix>/(lib/<arch>|lib|share)/cmake/<name>*/
<prefix>/(lib/<arch>|lib|share)/<name>*/
<prefix>/(lib/<arch>|lib|share)/<name>*/(cmake|CMake)/
<prefix>/<name>*/(lib/<arch>|lib|share)/cmake/<name>*/
<prefix>/<name>*/(lib/<arch>|lib|share)/<name>*/
<prefix>/<name>*/(lib/<arch>|lib|share)/<name>*/(cmake|CMake)/
```

catkin does not support all of them.

Why not?

**Comment by dirk-thomas** [comment]
`catkin` uses the vanilla CMake function `find_package` to find CMake config files from other packages: https://github.com/ros/catkin/blob/cbe836852a8cff82ed2be3e8ade4392d1694fc49/cmake/catkinConfig.cmake.in#L73-L92 The only thing "custom" is the parameter `NO_MODULE` since the goal is to find CMake config files and not modules. So I am not sure where `catkin` is supposed to "overrides this and hardcodes a subset of these locations".

**Comment by mamoll** [comment]
@dirk-thomas, this is where the paths are hard-coded:

https://github.com/ros/catkin/blob/kinetic-devel/cmake/catkinConfig.cmake.in#L68-L69

**Comment by dirk-thomas** [comment]
Oh right, since all passed `COMPONENTS` are expected to be catkin packages it is only checking in this locations since that is where `catkin_package` installs the generated CMake config files.

There are multiple options:
* Change the location of the CMake config file to match that path. That will make it work right away.
* Uses could use `find_package(ompl)` instead of using `find_package(catkin COMPONENTS ompl)`.
* `catkin` could be modified to also consider those locations. The first "downside" of this is that it can the be used to find arbitrary CMake packages which might not adhere to the conventions used in catkin packages (for all the expected variable names). The second one is that whatever change would be proposed would need to go through some testing and will not be ready to be release in time for the melodic release next week.

Therefore I would suggest proceeding with the first option.

**Comment by mamoll** [comment]
> Therefore I would suggest proceeding with the first option.

Yes, that is what I am planning to do for OMPL, since I don't have a strong preference one way or the other. @v4hn's point is that the problem will likely pop up again for other packages.

**Comment by v4hn** [comment]
> Uses could use find_package(ompl) instead of using find_package(catkin COMPONENTS ompl).

I believe this is the correct way to do it either way and personally if that works I don't see a bug in catkin.

@mamoll As far as I can see we don't use `COMPONENTS ompl` anywhere, but we use [`find_package(OMPL REQUIRED)`](https://github.com/ros-planning/moveit/blob/kinetic-devel/moveit_planners/ompl/CMakeLists.txt#L23).
Could this be an artifact because we don't use `find_package(ompl REQUIRED)` instead?

**Comment by dirk-thomas** [comment]
> Could this be an artifact because we don't use `find_package(ompl REQUIRED)` instead?

Since your CMake config file is named `omplConfig.cmake` the name is case sensitive. If you would like it to be case insensitive it would need to be `ompl-config.cmake` as far as I recall.

**Comment by mamoll** [comment]
@v4hn, yes, case matters. You should use `find_package(ompl REQUIRED)`. There is also an extended discussion about `find_package(catkin COMPONENT ompl)` vs. `find_package(ompl)` here: https://github.com/ros-planning/moveit/issues/169

**Comment by v4hn** [comment]
Ok, I consider this problem resolved for MoveIt after we changed to `find_package(ompl)`

One thing I still wonder about is whether there is a way to avoid this kind of confusion altogether by *not generating* the cmake config for `OMPL` / any third party module in the first place if the maintainers don't want them and distribute their own configs. The config is generated through bloom I guess?

@dirk-thomas Would be great if you could comment on that point, afterwards feel free to close this issue.

**Comment by dirk-thomas** [comment]
The CMake config file is generated by the `catkin_package` call. If you want to have one for your package you call it, if you don't you don't call the function. Then the package should probably have a build type of `cmake` instead of `catkin`.

**Comment by mamoll** [comment]
In the case of `ompl`, it generates its own cmake config file [using standard cmake macros](https://github.com/ompl/ompl/blob/8f8d627795e3b916241cb78d008beba354da621e/CMakeLists.txt#L195-L212):
```
if (NOT ${CMAKE_VERSION} VERSION_LESS 2.8.8)
    include(CMakePackageConfigHelpers)
    set(INCLUDE_INSTALL_DIR ${CMAKE_INSTALL_INCLUDEDIR})
    set(LIB_INSTALL_DIR ${CMAKE_INSTALL_LIBDIR})
    configure_package_config_file(omplConfig.cmake.in
        ${CMAKE_CURRENT_BINARY_DIR}/omplConfig.cmake
        INSTALL_DESTINATION ${CMAKE_INSTALL_DATAROOTDIR}/ompl/cmake
        PATH_VARS INCLUDE_INSTALL_DIR LIB_INSTALL_DIR
        NO_CHECK_REQUIRED_COMPONENTS_MACRO)
    write_basic_package_version_file(
        ${CMAKE_CURRENT_BINARY_DIR}/omplConfigVersion.cmake
        VERSION ${OMPL_VERSION}
        COMPATIBILITY SameMajorVersion)
    install(FILES ${CMAKE_CURRENT_BINARY_DIR}/omplConfig.cmake
        ${CMAKE_CURRENT_BINARY_DIR}/omplConfigVersion.cmake
        DESTINATION ${CMAKE_INSTALL_DATAROOTDIR}/ompl/cmake
        COMPONENT ompl)
endif()
```

**Comment by dirk-thomas** [comment]
I will go ahead and close this since there seems to be nothing to be done within catkin. Please feel free to continue commenting.
