### ISSUE TITLE
segmentation fault core dumped

### ISSUE THREAD

**Issue by ArkoK** [ros/catkin#944]
trying to use command " rosrun rqt_gui "

**Comment by dirk-thomas** [comment]
You might want to ask your question on answers.ros.org first. Please make sure to include more information in your question otherwise people can't really help you. Once it is clear that it is actually a bug you can create an issue in the repository related to the problem - this repo is certainly not the right place.

Please also take a look at the [ROS support guidelines](http://wiki.ros.org/Support).
