### ISSUE TITLE
incomplete support for passing cmake arguments

### ISSUE THREAD

**Issue by csukuangfj** [ros/catkin#945]
It is correct in cmake to do the following
```.cmake
cmake -D MY_OPTION=ON
```

and

```.cmake
cmake -DMY_OPTION=ON
```
That is, there can be either a space or no space between **`D`** and the **option**.

But `catkin_make` supports only

```.cmake
cmake --cmake-args -DMY_OPTION=ON
```

An error occurs if 
```.cmake
cmake --cmake-args -D MY_OPTION=ON
```
is used.

**Comment by dirk-thomas** [comment]
Currently only the "joined" syntax is supported simply because it is much easier to handle. Any arguments starting with `-D` are being passed to the CMake call (https://github.com/ros/catkin/blob/928c2025206e1a3f0d9d504ef5b26efe1cc95d8b/python/catkin/builder.py#L119).

Supporting the other syntax using multiple arguments should be doable. Is there a particular use case where you can't use the "joined" syntax?

Or is this only a nice-to-have? If that is the case I would ask you to consider contributing a pull request implementing support for the second syntax.

**Comment by dirk-thomas** [comment]
Since there was no further response I assume there is no interest to implement this enhancement. Therefore I will go ahead and close the ticket for now. Please feel free to provide a pull request for the suggested improvement.
