### ISSUE TITLE
Automatically run tests on ROS build farm for pure cmake project

### ISSUE THREAD

**Issue by awinkler** [ros/catkin#946]
Hi, I'm hosting a [pure cmake project ](http://build.ros.org/view/Kdev/job/Kdev__ifopt__ubuntu_xenial_amd64/)(not dependent on catkin) on the ROS build farm, for which I generate some unit test in my `CMakeLists.txt` similar to:

```cpp
find_package(GTest)
add_executable(test my_test.cpp)  
target_link_libraries(test ${GTEST_BOTH_LIBRARIES} pthread)
add_test(test test)
```
I can run these with `make test` after a non-catkin build, this works fine. 

**How can I tell the ROS build farm (which seems to be internally calling  `catkin_make run_tests`) to run my gtests as well after building.** 

I don't want _catkinize_ my  project in order to use the standard `catkin_add_gtest`, but keep allowing the standard `mkdir build; cd build; cmake ..` option. 

Thank you very much for your help!

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.

**Comment by awinkler** [comment]
Link to question:
https://answers.ros.org/question/296628/automatically-run-tests-on-ros-build-farm-for-pure-cmake-project/
