### ISSUE TITLE
rosdep can't find catkin

### ISSUE THREAD

**Issue by Achllle** [ros/catkin#947]
I'm shamelessly going to repost my [question on answers.ros.org](https://answers.ros.org/question/296593/importerror-catkin_pkg/) here because I can't do anything ROS anymore. 

Catkin was installed through the `ros-kinetic-desktop-full` install but the package can't be found with Python:
```
$ python -c 'import catkin_pkg'

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named catkin_pkg
```
Details on various settings and the location of the package are on the original question.

I can get it to work if I install using `pip install catkin_pkg` but that's not recommended and I'm worried that something is set up wrong so that future apt packages will also not be found.

This is likely to be a setup issue on my computer, but I'm not 100% sure so opening an issue here.

**Comment by sloretz** [comment]
Hi @Achllle, the python package `catkin_pkg` comes from https://github.com/ros-infrastructure/catkin_pkg

I'll close this issue since the question is about software in a different repo; however, I think  answers.ros.org is the best place. I added a comment on your question to continue the discussion there.
