### ISSUE TITLE
Cannot build new packages with catkin_make

### ISSUE THREAD

**Issue by Hellsgone** [ros/catkin#948]
Hi, I am working on the follower demo for TurtleBot 3 Burger and I came across with this problem. I have downloaded the required packages however I cannot build them it does not allow me to. I tried to run in isolated but that didn't work as well. It has to do something with the cartopgraher. Here are the terminal screen for that.
![screenshot_2](https://user-images.githubusercontent.com/41053677/42704337-5e2be92c-86c7-11e8-9135-fd55408fb8b5.png)
![screenshot_3](https://user-images.githubusercontent.com/41053677/42704340-5fd62f4e-86c7-11e8-8168-3cb2bacf3939.png)

Any clues? Thanks

**Comment by sloretz** [comment]
Hi @Hellsgone, per the [ROS support guidelines](http://wiki.ros.org/Support) would you mind asking this question at https://answers.ros.org? ROS answers has a larger audience that could answer your question.

When you do, please post the text from the terminal instead of a screenshot. Text is searchable and will help people with the same problem find your question in the future.

I'll close this for now. Feel free to add link to the question here to direct people to it.
