### ISSUE TITLE
Importing python module fails, need to run catkin_make twice

### ISSUE THREAD

**Issue by agutenkunst** [ros/catkin#974]
Somehow related to https://github.com/ros/catkin/issues/841 yet I am not sure if entirely the same.

I created a minimal example here: https://github.com/agutenkunst/bug_python_test_deps

If I start with a clean workspace and do
`catkin_make`
`catkin_make run_tests_bug_python_test_deps_rostest_test_foo_test.test`
it will fail with **ImportError: No module named bug_python_test_deps.foo**

If I now do a `touch build/CMakeCache.txt`
and run the test again with
`catkin_make run_tests_bug_python_test_deps_rostest_test_foo_test.test`
everything works fine.

Printing the pythonpath inside my test yields that at the second run a additional
**/home/[username]/catkin_ws/devel/lib/python2.7/dist-packages** 
appears in the path, which is exactly the missing location in the first run.

Is there something that I didn't get correct?

**Comment by jschleicher** [comment]
In your minimal example, sourcing `devel/setup.bash` after the first catkin_make also works (as suggested in #841):

But I totally agree, that a direct call of
```
catkin_make run_tests
```
shouldn't produce any errors. Any thoughts on how to address this issue?

**Comment by UltronDestroyer** [comment]
I came to this issue from https://github.com/ros/catkin/issues/841 and I looked into this further as it was quite a stupid annoyance.

I discovered that the issue comes from a combination of what users are sourcing (e.g source devel/setup.bash vs source devel/setup.sh) and how the environment variable CATKIN_SETUP_UTIL_ARGS is used.

The entire story is explained. Hold tight.

**If you want a tl;dr solution, simply wipe your devel/ build/ install/ directories and have this set in your ~/.bashrc OR if you want just a one off do _'`export CATKIN_SETUP_UTIL_ARGS=--extend'`_. Then, run catkin_make run_tests and you will see that everything is working fine and dandy. But why?**

Users most of the time use setup.bash, which doesn't pass down the --extend parameter anyway, so running source devel/setup.bash --extend, so that won't work as it is just a passthrough script which will call setup.sh. That's where the magic happens. setup.sh however does respect the --extend parameter and it also respects the env var CATKIN_SETUP_UTIL_ARGS which is why the above solution works. But what does --extend do and why does it cause things to work?

Looking inside _setup_util.py inside your devel directory, you will see that it can take an --extend param (discussed above). If its set, args.extend will be set to true, and so it will avoid the routine _rollback_env_variables. This function fucks everything up as it explicitly states (and does)

 "    For each catkin workspace in CMAKE_PREFIX_PATH remove the first entry from env[NAME] matching workspace + subfolder.
"

Well, if you look in the file you will see that CMAKE_PREFIX_PATH is most likely of the sort "$yourworkspace/devel/:$opt/ros/kinetic/" or something. The problem is that your workspace is first, and unless extend is set then it trims it off of the CMAKE_PREFIX_PATH, thus preventing your libraries from being found. This file generates an environment cache file which sticks around unless you add/remove new catkin packages and so if --extend isn't set, your path will continuously just not contain the proper $PYTHONPATH which includes your custom modules.

Now, this can all be completely avoided by doing @dirk-thomas solution in the linked issue because catkin_make_isolated will just take the env var from your existing shell, which is most likely correct because it wouldn't trim off your custom module path in its generated env cache.

I can't be fucked to make a PR to fix this workflow because the bashrc work around is fine for me, but if someone would do that I would be grateful that the default behaviour is changed.

Proof of it working when the --extend is passed in via env vars:
```
dash@dash:~/99robotics$ sudo rm -rf build devel
dash@dash:~/99robotics$ echo $CATKIN_S
$CATKIN_SETUP_UTIL_ARGS  $CATKIN_SHELL            
dash@dash:~/99robotics$ echo $CATKIN_SETUP_UTIL_ARGS 
--extend
dash@dash:~/99robotics$ catkin_make run_tests
Base path: /home/dash/99robotics
Source space: /home/dash/99robotics/src
Build space: /home/dash/99robotics/build
Devel space: /home/dash/99robotics/devel
Install space: /home/dash/99robotics/install
####
#### Running command: "cmake /home/dash/99robotics/src -DCATKIN_DEVEL_PREFIX=/home/dash/99robotics/devel -DCMAKE_INSTALL_PREFIX=/home/dash/99robotics/install -G Unix Makefiles" in "/home/dash/99robotics/build"
####
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using CATKIN_DEVEL_PREFIX: /home/dash/99robotics/devel
-- Using CMAKE_PREFIX_PATH: /home/dash/99robotics/devel;/home/dash/contracting/shield/code/pikachu/workspace/devel;/opt/ros/kinetic
-- This workspace overlays: /home/dash/99robotics/devel;/home/dash/contracting/shield/code/pikachu/workspace/devel;/opt/ros/kinetic
-- Found PythonInterp: /usr/bin/python (found version "2.7.12") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/dash/99robotics/build/test_results
-- Found gtest: gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.7.14
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 2 packages in topological order:
-- ~~  - robot_library
-- ~~  - rosdesigner
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin package: 'robot_library'
-- ==> add_subdirectory(ros_easy/robot_library)
-- +++ processing catkin package: 'rosdesigner'
-- ==> add_subdirectory(ros_easy/rosdesigner)
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dash/99robotics/build
####
#### Running command: "make run_tests -j16 -l16" in "/home/dash/99robotics/build"
####
Scanning dependencies of target clean_test_results_rosdesigner
Scanning dependencies of target tests
Built target tests
Removing test result files from '/home/dash/99robotics/build/test_results/rosdesigner'
Built target clean_test_results_rosdesigner
Scanning dependencies of target _run_tests_rosdesigner_nosetests_tests.test_insert_button.py
-- run_tests.py: execute commands
  /usr/bin/cmake -E make_directory /home/dash/99robotics/build/test_results/rosdesigner
  /usr/bin/nosetests-2.7 -P --process-timeout=60 /home/dash/99robotics/src/ros_easy/rosdesigner/tests/test_insert_button.py --with-xunit --xunit-file=/home/dash/99robotics/build/test_results/rosdesigner/nosetests-tests.test_insert_button.py.xml
.E..QWidget: Must construct a QApplication before a QWidget
Aborted (core dumped)
-- run_tests.py: verify result "/home/dash/99robotics/build/test_results/rosdesigner/nosetests-tests.test_insert_button.py.xml"
Cannot find results, writing failure results to '/home/dash/99robotics/build/test_results/rosdesigner/MISSING-nosetests-tests.test_insert_button.py.xml'
Built target _run_tests_rosdesigner_nosetests_tests.test_insert_button.py
Scanning dependencies of target _run_tests_rosdesigner_nosetests
Built target _run_tests_rosdesigner_nosetests
Scanning dependencies of target _run_tests_rosdesigner
Built target _run_tests_rosdesigner
Scanning dependencies of target run_tests
Built target run_tests

```

Proof of it not working when the env var is not set:
```
dash@dash:~/99robotics$ echo $CATKIN_SETUP_UTIL_ARGS 
--extend
dash@dash:~/99robotics$ echo $CATKIN_SETUP_UTIL_ARGS ^C
dash@dash:~/99robotics$ export ^C
dash@dash:~/99robotics$ echo $CATKIN_SETUP_UTIL_ARGS 
--extend
dash@dash:~/99robotics$ export CATKIN_SETUP_UTIL_ARGS=''
dash@dash:~/99robotics$ catkin_make run_^C
dash@dash:~/99robotics$ sudo rm -rf build devel
dash@dash:~/99robotics$ catkin_make run_tests
Base path: /home/dash/99robotics
Source space: /home/dash/99robotics/src
Build space: /home/dash/99robotics/build
Devel space: /home/dash/99robotics/devel
Install space: /home/dash/99robotics/install
####
#### Running command: "cmake /home/dash/99robotics/src -DCATKIN_DEVEL_PREFIX=/home/dash/99robotics/devel -DCMAKE_INSTALL_PREFIX=/home/dash/99robotics/install -G Unix Makefiles" in "/home/dash/99robotics/build"
####
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using CATKIN_DEVEL_PREFIX: /home/dash/99robotics/devel
-- Using CMAKE_PREFIX_PATH: /home/dash/99robotics/devel;/home/dash/contracting/shield/code/pikachu/workspace/devel;/opt/ros/kinetic
-- This workspace overlays: /home/dash/99robotics/devel;/home/dash/contracting/shield/code/pikachu/workspace/devel;/opt/ros/kinetic
-- Found PythonInterp: /usr/bin/python (found version "2.7.12") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/dash/99robotics/build/test_results
-- Found gtest: gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.7.14
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 2 packages in topological order:
-- ~~  - robot_library
-- ~~  - rosdesigner
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin package: 'robot_library'
-- ==> add_subdirectory(ros_easy/robot_library)
-- +++ processing catkin package: 'rosdesigner'
-- ==> add_subdirectory(ros_easy/rosdesigner)
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dash/99robotics/build
####
#### Running command: "make run_tests -j16 -l16" in "/home/dash/99robotics/build"
####
Scanning dependencies of target tests
Scanning dependencies of target clean_test_results_rosdesigner
Built target tests
Removing test result files from '/home/dash/99robotics/build/test_results/rosdesigner'
Built target clean_test_results_rosdesigner
Scanning dependencies of target _run_tests_rosdesigner_nosetests_tests.test_insert_button.py
-- run_tests.py: execute commands
  /usr/bin/cmake -E make_directory /home/dash/99robotics/build/test_results/rosdesigner
  /usr/bin/nosetests-2.7 -P --process-timeout=60 /home/dash/99robotics/src/ros_easy/rosdesigner/tests/test_insert_button.py --with-xunit --xunit-file=/home/dash/99robotics/build/test_results/rosdesigner/nosetests-tests.test_insert_button.py.xml
E
======================================================================
ERROR: Failure: ImportError (No module named rosdesigner.widgets.toolbarbuttons)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/dash/99robotics/src/ros_easy/rosdesigner/tests/test_insert_button.py", line 11, in <module>
    from rosdesigner.widgets.toolbarbuttons import *
ImportError: No module named rosdesigner.widgets.toolbarbuttons
-------------------- >> begin captured logging << --------------------
rospy.topics: INFO: topicmanager initialized
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
-- run_tests.py: verify result "/home/dash/99robotics/build/test_results/rosdesigner/nosetests-tests.test_insert_button.py.xml"
Built target _run_tests_rosdesigner_nosetests_tests.test_insert_button.py
Scanning dependencies of target _run_tests_rosdesigner_nosetests
Built target _run_tests_rosdesigner_nosetests
Scanning dependencies of target _run_tests_rosdesigner
Built target _run_tests_rosdesigner
Scanning dependencies of target run_tests
Built target run_tests

```



@dirk-thomas @jschleicher

**Comment by DamKoVosh** [comment]
I can confirm the issue and workaround: 'export CATKIN_SETUP_UTIL_ARGS=--extend'

**Comment by dirk-thomas** [comment]
> Somehow related to #841 yet I am not sure if entirely the same.

> If I start with a clean workspace and do
> `catkin_make`
> `catkin_make run_tests_bug_python_test_deps_rostest_test_foo_test.test`
> it will fail with `ImportError: No module named bug_python_test_deps.foo`

@agutenkunst The workaround described in the [referenced ticket](https://github.com/ros/catkin/issues/841#issuecomment-275467002) (sourcing `devel/setup.bash` between the two `catkin_make` invocations) seems to work just fine (at least for me). Please double check if that is the case for you too.

**Comment by dirk-thomas** [comment]
@TheDash Your case is different - you are building different packages and invoke different commands therefore you can't compare the result with the one of the original author of this ticket.

When setting `CATKIN_SETUP_UTIL_ARGS` it does *not* fix the problem for the originally reported case. I would also highly suggest not to do that since it changes the behavior in a way which it is not intended for.

Also in order to be able to reproduce your case you need to provide complete steps, e.g. including the repos you are trying to build.

**Comment by dirk-thomas** [comment]
I created #986 which addresses the originally reported problem from @agutenkunst for me.

@agutenkunst Please give it a try with the patch and comment if it resolves the problem for you to. @TheDash Please also try the proposed patch for your use case (which I couldn't try since the steps to reproduce are unclear).
